//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bi_links
    {
        public int id { get; set; }
        public string user_no { get; set; }
        public string user_name { get; set; }
        public string link_name { get; set; }
        public string server_name { get; set; }
        public string login_name { get; set; }
        public string login_password { get; set; }
        public System.DateTime update_time { get; set; }
        public bool share_flag { get; set; }
    }
}
