//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dn_shoppingCar
    {
        public int id { get; set; }
        public string user_no { get; set; }
        public Nullable<int> dish_id { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<System.DateTime> in_time { get; set; }
        public Nullable<bool> is_submit { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<bool> is_delete { get; set; }
        public Nullable<System.DateTime> delete_time { get; set; }
        public Nullable<bool> is_checked { get; set; }
        public Nullable<decimal> benefit_price { get; set; }
        public string benefit_info { get; set; }
        public string res_no { get; set; }
    
        public virtual dn_dishes dn_dishes { get; set; }
        public virtual dn_order dn_order { get; set; }
    }
}
