#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LogisticsDB")]
	public partial class DormDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertdormitory_area(dormitory_area instance);
    partial void Updatedormitory_area(dormitory_area instance);
    partial void Deletedormitory_area(dormitory_area instance);
    partial void Insertdormitory_dorm(dormitory_dorm instance);
    partial void Updatedormitory_dorm(dormitory_dorm instance);
    partial void Deletedormitory_dorm(dormitory_dorm instance);
    partial void Insertdormitory_employee(dormitory_employee instance);
    partial void Updatedormitory_employee(dormitory_employee instance);
    partial void Deletedormitory_employee(dormitory_employee instance);
    partial void Insertdormitory_event_log(dormitory_event_log instance);
    partial void Updatedormitory_event_log(dormitory_event_log instance);
    partial void Deletedormitory_event_log(dormitory_event_log instance);
    partial void Insertdormitory_lodging(dormitory_lodging instance);
    partial void Updatedormitory_lodging(dormitory_lodging instance);
    partial void Deletedormitory_lodging(dormitory_lodging instance);
    partial void Insertdormitory_other_fee(dormitory_other_fee instance);
    partial void Updatedormitory_other_fee(dormitory_other_fee instance);
    partial void Deletedormitory_other_fee(dormitory_other_fee instance);
    partial void Insertdormitory_type(dormitory_type instance);
    partial void Updatedormitory_type(dormitory_type instance);
    partial void Deletedormitory_type(dormitory_type instance);
    #endregion
		
		public DormDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LogisticsDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DormDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DormDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DormDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DormDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<dormitory_area> dormitory_area
		{
			get
			{
				return this.GetTable<dormitory_area>();
			}
		}
		
		public System.Data.Linq.Table<dormitory_dorm> dormitory_dorm
		{
			get
			{
				return this.GetTable<dormitory_dorm>();
			}
		}
		
		public System.Data.Linq.Table<dormitory_employee> dormitory_employee
		{
			get
			{
				return this.GetTable<dormitory_employee>();
			}
		}
		
		public System.Data.Linq.Table<dormitory_event_log> dormitory_event_log
		{
			get
			{
				return this.GetTable<dormitory_event_log>();
			}
		}
		
		public System.Data.Linq.Table<dormitory_lodging> dormitory_lodging
		{
			get
			{
				return this.GetTable<dormitory_lodging>();
			}
		}
		
		public System.Data.Linq.Table<dormitory_other_fee> dormitory_other_fee
		{
			get
			{
				return this.GetTable<dormitory_other_fee>();
			}
		}
		
		public System.Data.Linq.Table<dormitory_type> dormitory_type
		{
			get
			{
				return this.GetTable<dormitory_type>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dormitory_area")]
	public partial class dormitory_area : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _comment;
		
		private EntitySet<dormitory_dorm> _dormitory_dorm;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OncommentChanging(string value);
    partial void OncommentChanged();
    #endregion
		
		public dormitory_area()
		{
			this._dormitory_dorm = new EntitySet<dormitory_dorm>(new Action<dormitory_dorm>(this.attach_dormitory_dorm), new Action<dormitory_dorm>(this.detach_dormitory_dorm));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(20)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="VarChar(200)")]
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				if ((this._comment != value))
				{
					this.OncommentChanging(value);
					this.SendPropertyChanging();
					this._comment = value;
					this.SendPropertyChanged("comment");
					this.OncommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dormitory_area_dormitory_dorm", Storage="_dormitory_dorm", ThisKey="id", OtherKey="area_number")]
		public EntitySet<dormitory_dorm> dormitory_dorm
		{
			get
			{
				return this._dormitory_dorm;
			}
			set
			{
				this._dormitory_dorm.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_dormitory_dorm(dormitory_dorm entity)
		{
			this.SendPropertyChanging();
			entity.dormitory_area = this;
		}
		
		private void detach_dormitory_dorm(dormitory_dorm entity)
		{
			this.SendPropertyChanging();
			entity.dormitory_area = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dormitory_dorm")]
	public partial class dormitory_dorm : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _number;
		
		private System.Nullable<int> _area_number;
		
		private System.Nullable<int> _type_id;
		
		private System.Nullable<short> _available;
		
		private string _comment;
		
		private string _dorm_sex;
		
		private System.Nullable<decimal> _rent;
		
		private System.Nullable<decimal> _manage_cost;
		
		private string _for_order;
		
		private EntitySet<dormitory_lodging> _dormitory_lodging;
		
		private EntitySet<dormitory_other_fee> _dormitory_other_fee;
		
		private EntityRef<dormitory_area> _dormitory_area;
		
		private EntityRef<dormitory_type> _dormitory_type;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnumberChanging(string value);
    partial void OnnumberChanged();
    partial void Onarea_numberChanging(System.Nullable<int> value);
    partial void Onarea_numberChanged();
    partial void Ontype_idChanging(System.Nullable<int> value);
    partial void Ontype_idChanged();
    partial void OnavailableChanging(System.Nullable<short> value);
    partial void OnavailableChanged();
    partial void OncommentChanging(string value);
    partial void OncommentChanged();
    partial void Ondorm_sexChanging(string value);
    partial void Ondorm_sexChanged();
    partial void OnrentChanging(System.Nullable<decimal> value);
    partial void OnrentChanged();
    partial void Onmanage_costChanging(System.Nullable<decimal> value);
    partial void Onmanage_costChanged();
    partial void Onfor_orderChanging(string value);
    partial void Onfor_orderChanged();
    #endregion
		
		public dormitory_dorm()
		{
			this._dormitory_lodging = new EntitySet<dormitory_lodging>(new Action<dormitory_lodging>(this.attach_dormitory_lodging), new Action<dormitory_lodging>(this.detach_dormitory_lodging));
			this._dormitory_other_fee = new EntitySet<dormitory_other_fee>(new Action<dormitory_other_fee>(this.attach_dormitory_other_fee), new Action<dormitory_other_fee>(this.detach_dormitory_other_fee));
			this._dormitory_area = default(EntityRef<dormitory_area>);
			this._dormitory_type = default(EntityRef<dormitory_type>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number", DbType="VarChar(50)")]
		public string number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this.OnnumberChanging(value);
					this.SendPropertyChanging();
					this._number = value;
					this.SendPropertyChanged("number");
					this.OnnumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area_number", DbType="Int")]
		public System.Nullable<int> area_number
		{
			get
			{
				return this._area_number;
			}
			set
			{
				if ((this._area_number != value))
				{
					if (this._dormitory_area.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onarea_numberChanging(value);
					this.SendPropertyChanging();
					this._area_number = value;
					this.SendPropertyChanged("area_number");
					this.Onarea_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_id", DbType="Int")]
		public System.Nullable<int> type_id
		{
			get
			{
				return this._type_id;
			}
			set
			{
				if ((this._type_id != value))
				{
					if (this._dormitory_type.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontype_idChanging(value);
					this.SendPropertyChanging();
					this._type_id = value;
					this.SendPropertyChanged("type_id");
					this.Ontype_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_available", DbType="SmallInt")]
		public System.Nullable<short> available
		{
			get
			{
				return this._available;
			}
			set
			{
				if ((this._available != value))
				{
					this.OnavailableChanging(value);
					this.SendPropertyChanging();
					this._available = value;
					this.SendPropertyChanged("available");
					this.OnavailableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="VarChar(200)")]
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				if ((this._comment != value))
				{
					this.OncommentChanging(value);
					this.SendPropertyChanging();
					this._comment = value;
					this.SendPropertyChanged("comment");
					this.OncommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dorm_sex", DbType="VarChar(8)")]
		public string dorm_sex
		{
			get
			{
				return this._dorm_sex;
			}
			set
			{
				if ((this._dorm_sex != value))
				{
					this.Ondorm_sexChanging(value);
					this.SendPropertyChanging();
					this._dorm_sex = value;
					this.SendPropertyChanged("dorm_sex");
					this.Ondorm_sexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rent", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> rent
		{
			get
			{
				return this._rent;
			}
			set
			{
				if ((this._rent != value))
				{
					this.OnrentChanging(value);
					this.SendPropertyChanging();
					this._rent = value;
					this.SendPropertyChanged("rent");
					this.OnrentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manage_cost", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> manage_cost
		{
			get
			{
				return this._manage_cost;
			}
			set
			{
				if ((this._manage_cost != value))
				{
					this.Onmanage_costChanging(value);
					this.SendPropertyChanging();
					this._manage_cost = value;
					this.SendPropertyChanged("manage_cost");
					this.Onmanage_costChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_for_order", DbType="VarChar(50)")]
		public string for_order
		{
			get
			{
				return this._for_order;
			}
			set
			{
				if ((this._for_order != value))
				{
					this.Onfor_orderChanging(value);
					this.SendPropertyChanging();
					this._for_order = value;
					this.SendPropertyChanged("for_order");
					this.Onfor_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dormitory_dorm_dormitory_lodging", Storage="_dormitory_lodging", ThisKey="id", OtherKey="dorm_id")]
		public EntitySet<dormitory_lodging> dormitory_lodging
		{
			get
			{
				return this._dormitory_lodging;
			}
			set
			{
				this._dormitory_lodging.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dormitory_dorm_dormitory_other_fee", Storage="_dormitory_other_fee", ThisKey="id", OtherKey="dorm_id")]
		public EntitySet<dormitory_other_fee> dormitory_other_fee
		{
			get
			{
				return this._dormitory_other_fee;
			}
			set
			{
				this._dormitory_other_fee.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dormitory_area_dormitory_dorm", Storage="_dormitory_area", ThisKey="area_number", OtherKey="id", IsForeignKey=true)]
		public dormitory_area dormitory_area
		{
			get
			{
				return this._dormitory_area.Entity;
			}
			set
			{
				dormitory_area previousValue = this._dormitory_area.Entity;
				if (((previousValue != value) 
							|| (this._dormitory_area.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dormitory_area.Entity = null;
						previousValue.dormitory_dorm.Remove(this);
					}
					this._dormitory_area.Entity = value;
					if ((value != null))
					{
						value.dormitory_dorm.Add(this);
						this._area_number = value.id;
					}
					else
					{
						this._area_number = default(Nullable<int>);
					}
					this.SendPropertyChanged("dormitory_area");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dormitory_type_dormitory_dorm", Storage="_dormitory_type", ThisKey="type_id", OtherKey="id", IsForeignKey=true)]
		public dormitory_type dormitory_type
		{
			get
			{
				return this._dormitory_type.Entity;
			}
			set
			{
				dormitory_type previousValue = this._dormitory_type.Entity;
				if (((previousValue != value) 
							|| (this._dormitory_type.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dormitory_type.Entity = null;
						previousValue.dormitory_dorm.Remove(this);
					}
					this._dormitory_type.Entity = value;
					if ((value != null))
					{
						value.dormitory_dorm.Add(this);
						this._type_id = value.id;
					}
					else
					{
						this._type_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("dormitory_type");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_dormitory_lodging(dormitory_lodging entity)
		{
			this.SendPropertyChanging();
			entity.dormitory_dorm = this;
		}
		
		private void detach_dormitory_lodging(dormitory_lodging entity)
		{
			this.SendPropertyChanging();
			entity.dormitory_dorm = null;
		}
		
		private void attach_dormitory_other_fee(dormitory_other_fee entity)
		{
			this.SendPropertyChanging();
			entity.dormitory_dorm = this;
		}
		
		private void detach_dormitory_other_fee(dormitory_other_fee entity)
		{
			this.SendPropertyChanging();
			entity.dormitory_dorm = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dormitory_employee")]
	public partial class dormitory_employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _card_number;
		
		private string _account_number;
		
		private string _identify_number;
		
		private string _sex;
		
		private string _degree;
		
		private System.Nullable<int> _department;
		
		private string _household;
		
		private string _salary_type;
		
		private string _phone;
		
		private string _family_address;
		
		private string _family_phone;
		
		private string _family_connector;
		
		private string _comment;
		
		private System.Data.Linq.Binary _picture;
		
		private System.Nullable<int> _old_id;
		
		private string _identify_info;
		
		private string _key_num;
		
		private EntitySet<dormitory_lodging> _dormitory_lodging;
		
		private EntitySet<dormitory_other_fee> _dormitory_other_fee;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Oncard_numberChanging(string value);
    partial void Oncard_numberChanged();
    partial void Onaccount_numberChanging(string value);
    partial void Onaccount_numberChanged();
    partial void Onidentify_numberChanging(string value);
    partial void Onidentify_numberChanged();
    partial void OnsexChanging(string value);
    partial void OnsexChanged();
    partial void OndegreeChanging(string value);
    partial void OndegreeChanged();
    partial void OndepartmentChanging(System.Nullable<int> value);
    partial void OndepartmentChanged();
    partial void OnhouseholdChanging(string value);
    partial void OnhouseholdChanged();
    partial void Onsalary_typeChanging(string value);
    partial void Onsalary_typeChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void Onfamily_addressChanging(string value);
    partial void Onfamily_addressChanged();
    partial void Onfamily_phoneChanging(string value);
    partial void Onfamily_phoneChanged();
    partial void Onfamily_connectorChanging(string value);
    partial void Onfamily_connectorChanged();
    partial void OncommentChanging(string value);
    partial void OncommentChanged();
    partial void OnpictureChanging(System.Data.Linq.Binary value);
    partial void OnpictureChanged();
    partial void Onold_idChanging(System.Nullable<int> value);
    partial void Onold_idChanged();
    partial void Onidentify_infoChanging(string value);
    partial void Onidentify_infoChanged();
    partial void Onkey_numChanging(string value);
    partial void Onkey_numChanged();
    #endregion
		
		public dormitory_employee()
		{
			this._dormitory_lodging = new EntitySet<dormitory_lodging>(new Action<dormitory_lodging>(this.attach_dormitory_lodging), new Action<dormitory_lodging>(this.detach_dormitory_lodging));
			this._dormitory_other_fee = new EntitySet<dormitory_other_fee>(new Action<dormitory_other_fee>(this.attach_dormitory_other_fee), new Action<dormitory_other_fee>(this.detach_dormitory_other_fee));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(40)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_card_number", DbType="VarChar(20)")]
		public string card_number
		{
			get
			{
				return this._card_number;
			}
			set
			{
				if ((this._card_number != value))
				{
					this.Oncard_numberChanging(value);
					this.SendPropertyChanging();
					this._card_number = value;
					this.SendPropertyChanged("card_number");
					this.Oncard_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account_number", DbType="VarChar(50)")]
		public string account_number
		{
			get
			{
				return this._account_number;
			}
			set
			{
				if ((this._account_number != value))
				{
					this.Onaccount_numberChanging(value);
					this.SendPropertyChanging();
					this._account_number = value;
					this.SendPropertyChanged("account_number");
					this.Onaccount_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identify_number", DbType="VarChar(20)")]
		public string identify_number
		{
			get
			{
				return this._identify_number;
			}
			set
			{
				if ((this._identify_number != value))
				{
					this.Onidentify_numberChanging(value);
					this.SendPropertyChanging();
					this._identify_number = value;
					this.SendPropertyChanged("identify_number");
					this.Onidentify_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="VarChar(2)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this.OnsexChanging(value);
					this.SendPropertyChanging();
					this._sex = value;
					this.SendPropertyChanged("sex");
					this.OnsexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_degree", DbType="VarChar(10)")]
		public string degree
		{
			get
			{
				return this._degree;
			}
			set
			{
				if ((this._degree != value))
				{
					this.OndegreeChanging(value);
					this.SendPropertyChanging();
					this._degree = value;
					this.SendPropertyChanged("degree");
					this.OndegreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department", DbType="Int")]
		public System.Nullable<int> department
		{
			get
			{
				return this._department;
			}
			set
			{
				if ((this._department != value))
				{
					this.OndepartmentChanging(value);
					this.SendPropertyChanging();
					this._department = value;
					this.SendPropertyChanged("department");
					this.OndepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_household", DbType="VarChar(100)")]
		public string household
		{
			get
			{
				return this._household;
			}
			set
			{
				if ((this._household != value))
				{
					this.OnhouseholdChanging(value);
					this.SendPropertyChanging();
					this._household = value;
					this.SendPropertyChanged("household");
					this.OnhouseholdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salary_type", DbType="VarChar(50)")]
		public string salary_type
		{
			get
			{
				return this._salary_type;
			}
			set
			{
				if ((this._salary_type != value))
				{
					this.Onsalary_typeChanging(value);
					this.SendPropertyChanging();
					this._salary_type = value;
					this.SendPropertyChanged("salary_type");
					this.Onsalary_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(50)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_family_address", DbType="VarChar(100)")]
		public string family_address
		{
			get
			{
				return this._family_address;
			}
			set
			{
				if ((this._family_address != value))
				{
					this.Onfamily_addressChanging(value);
					this.SendPropertyChanging();
					this._family_address = value;
					this.SendPropertyChanged("family_address");
					this.Onfamily_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_family_phone", DbType="VarChar(50)")]
		public string family_phone
		{
			get
			{
				return this._family_phone;
			}
			set
			{
				if ((this._family_phone != value))
				{
					this.Onfamily_phoneChanging(value);
					this.SendPropertyChanging();
					this._family_phone = value;
					this.SendPropertyChanged("family_phone");
					this.Onfamily_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_family_connector", DbType="VarChar(20)")]
		public string family_connector
		{
			get
			{
				return this._family_connector;
			}
			set
			{
				if ((this._family_connector != value))
				{
					this.Onfamily_connectorChanging(value);
					this.SendPropertyChanging();
					this._family_connector = value;
					this.SendPropertyChanged("family_connector");
					this.Onfamily_connectorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="VarChar(200)")]
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				if ((this._comment != value))
				{
					this.OncommentChanging(value);
					this.SendPropertyChanging();
					this._comment = value;
					this.SendPropertyChanged("comment");
					this.OncommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_picture", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary picture
		{
			get
			{
				return this._picture;
			}
			set
			{
				if ((this._picture != value))
				{
					this.OnpictureChanging(value);
					this.SendPropertyChanging();
					this._picture = value;
					this.SendPropertyChanged("picture");
					this.OnpictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_old_id", DbType="Int")]
		public System.Nullable<int> old_id
		{
			get
			{
				return this._old_id;
			}
			set
			{
				if ((this._old_id != value))
				{
					this.Onold_idChanging(value);
					this.SendPropertyChanging();
					this._old_id = value;
					this.SendPropertyChanged("old_id");
					this.Onold_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identify_info", DbType="VarChar(200)")]
		public string identify_info
		{
			get
			{
				return this._identify_info;
			}
			set
			{
				if ((this._identify_info != value))
				{
					this.Onidentify_infoChanging(value);
					this.SendPropertyChanging();
					this._identify_info = value;
					this.SendPropertyChanged("identify_info");
					this.Onidentify_infoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_key_num", DbType="NVarChar(500)")]
		public string key_num
		{
			get
			{
				return this._key_num;
			}
			set
			{
				if ((this._key_num != value))
				{
					this.Onkey_numChanging(value);
					this.SendPropertyChanging();
					this._key_num = value;
					this.SendPropertyChanged("key_num");
					this.Onkey_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dormitory_employee_dormitory_lodging", Storage="_dormitory_lodging", ThisKey="id", OtherKey="emp_id")]
		public EntitySet<dormitory_lodging> dormitory_lodging
		{
			get
			{
				return this._dormitory_lodging;
			}
			set
			{
				this._dormitory_lodging.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dormitory_employee_dormitory_other_fee", Storage="_dormitory_other_fee", ThisKey="id", OtherKey="emp_id")]
		public EntitySet<dormitory_other_fee> dormitory_other_fee
		{
			get
			{
				return this._dormitory_other_fee;
			}
			set
			{
				this._dormitory_other_fee.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_dormitory_lodging(dormitory_lodging entity)
		{
			this.SendPropertyChanging();
			entity.dormitory_employee = this;
		}
		
		private void detach_dormitory_lodging(dormitory_lodging entity)
		{
			this.SendPropertyChanging();
			entity.dormitory_employee = null;
		}
		
		private void attach_dormitory_other_fee(dormitory_other_fee entity)
		{
			this.SendPropertyChanging();
			entity.dormitory_employee = this;
		}
		
		private void detach_dormitory_other_fee(dormitory_other_fee entity)
		{
			this.SendPropertyChanging();
			entity.dormitory_employee = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dormitory_event_log")]
	public partial class dormitory_event_log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _model;
		
		private string _area;
		
		private string _dorm;
		
		private string _emp;
		
		private string _event;
		
		private string _operator;
		
		private System.Nullable<System.DateTime> _operate_time;
		
		private System.Nullable<bool> _is_normal;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmodelChanging(string value);
    partial void OnmodelChanged();
    partial void OnareaChanging(string value);
    partial void OnareaChanged();
    partial void OndormChanging(string value);
    partial void OndormChanged();
    partial void OnempChanging(string value);
    partial void OnempChanged();
    partial void OneventChanging(string value);
    partial void OneventChanged();
    partial void OnoperatorChanging(string value);
    partial void OnoperatorChanged();
    partial void Onoperate_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onoperate_timeChanged();
    partial void Onis_normalChanging(System.Nullable<bool> value);
    partial void Onis_normalChanged();
    #endregion
		
		public dormitory_event_log()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="VarChar(50)")]
		public string model
		{
			get
			{
				return this._model;
			}
			set
			{
				if ((this._model != value))
				{
					this.OnmodelChanging(value);
					this.SendPropertyChanging();
					this._model = value;
					this.SendPropertyChanged("model");
					this.OnmodelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area", DbType="VarChar(10)")]
		public string area
		{
			get
			{
				return this._area;
			}
			set
			{
				if ((this._area != value))
				{
					this.OnareaChanging(value);
					this.SendPropertyChanging();
					this._area = value;
					this.SendPropertyChanged("area");
					this.OnareaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dorm", DbType="VarChar(10)")]
		public string dorm
		{
			get
			{
				return this._dorm;
			}
			set
			{
				if ((this._dorm != value))
				{
					this.OndormChanging(value);
					this.SendPropertyChanging();
					this._dorm = value;
					this.SendPropertyChanged("dorm");
					this.OndormChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp", DbType="VarChar(50)")]
		public string emp
		{
			get
			{
				return this._emp;
			}
			set
			{
				if ((this._emp != value))
				{
					this.OnempChanging(value);
					this.SendPropertyChanging();
					this._emp = value;
					this.SendPropertyChanged("emp");
					this.OnempChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="event", Storage="_event", DbType="VarChar(500)")]
		public string @event
		{
			get
			{
				return this._event;
			}
			set
			{
				if ((this._event != value))
				{
					this.OneventChanging(value);
					this.SendPropertyChanging();
					this._event = value;
					this.SendPropertyChanged("@event");
					this.OneventChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="operator", Storage="_operator", DbType="VarChar(20)")]
		public string @operator
		{
			get
			{
				return this._operator;
			}
			set
			{
				if ((this._operator != value))
				{
					this.OnoperatorChanging(value);
					this.SendPropertyChanging();
					this._operator = value;
					this.SendPropertyChanged("@operator");
					this.OnoperatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operate_time", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> operate_time
		{
			get
			{
				return this._operate_time;
			}
			set
			{
				if ((this._operate_time != value))
				{
					this.Onoperate_timeChanging(value);
					this.SendPropertyChanging();
					this._operate_time = value;
					this.SendPropertyChanged("operate_time");
					this.Onoperate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_normal", DbType="Bit")]
		public System.Nullable<bool> is_normal
		{
			get
			{
				return this._is_normal;
			}
			set
			{
				if ((this._is_normal != value))
				{
					this.Onis_normalChanging(value);
					this.SendPropertyChanging();
					this._is_normal = value;
					this.SendPropertyChanged("is_normal");
					this.Onis_normalChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dormitory_lodging")]
	public partial class dormitory_lodging : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _dorm_id;
		
		private System.Nullable<int> _emp_id;
		
		private System.Nullable<System.DateTime> _in_date;
		
		private System.Nullable<System.DateTime> _out_date;
		
		private System.Nullable<decimal> _real_rent;
		
		private System.Nullable<decimal> _real_manage;
		
		private System.Nullable<decimal> _guarantee;
		
		private string _situation;
		
		private string _classify_property;
		
		private System.Nullable<bool> _is_quit;
		
		private System.Nullable<bool> _not_to_salary;
		
		private EntityRef<dormitory_dorm> _dormitory_dorm;
		
		private EntityRef<dormitory_employee> _dormitory_employee;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Ondorm_idChanging(System.Nullable<int> value);
    partial void Ondorm_idChanged();
    partial void Onemp_idChanging(System.Nullable<int> value);
    partial void Onemp_idChanged();
    partial void Onin_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onin_dateChanged();
    partial void Onout_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onout_dateChanged();
    partial void Onreal_rentChanging(System.Nullable<decimal> value);
    partial void Onreal_rentChanged();
    partial void Onreal_manageChanging(System.Nullable<decimal> value);
    partial void Onreal_manageChanged();
    partial void OnguaranteeChanging(System.Nullable<decimal> value);
    partial void OnguaranteeChanged();
    partial void OnsituationChanging(string value);
    partial void OnsituationChanged();
    partial void Onclassify_propertyChanging(string value);
    partial void Onclassify_propertyChanged();
    partial void Onis_quitChanging(System.Nullable<bool> value);
    partial void Onis_quitChanged();
    partial void Onnot_to_salaryChanging(System.Nullable<bool> value);
    partial void Onnot_to_salaryChanged();
    #endregion
		
		public dormitory_lodging()
		{
			this._dormitory_dorm = default(EntityRef<dormitory_dorm>);
			this._dormitory_employee = default(EntityRef<dormitory_employee>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dorm_id", DbType="Int")]
		public System.Nullable<int> dorm_id
		{
			get
			{
				return this._dorm_id;
			}
			set
			{
				if ((this._dorm_id != value))
				{
					if (this._dormitory_dorm.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondorm_idChanging(value);
					this.SendPropertyChanging();
					this._dorm_id = value;
					this.SendPropertyChanged("dorm_id");
					this.Ondorm_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_id", DbType="Int")]
		public System.Nullable<int> emp_id
		{
			get
			{
				return this._emp_id;
			}
			set
			{
				if ((this._emp_id != value))
				{
					if (this._dormitory_employee.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onemp_idChanging(value);
					this.SendPropertyChanging();
					this._emp_id = value;
					this.SendPropertyChanged("emp_id");
					this.Onemp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_in_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> in_date
		{
			get
			{
				return this._in_date;
			}
			set
			{
				if ((this._in_date != value))
				{
					this.Onin_dateChanging(value);
					this.SendPropertyChanging();
					this._in_date = value;
					this.SendPropertyChanged("in_date");
					this.Onin_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_out_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> out_date
		{
			get
			{
				return this._out_date;
			}
			set
			{
				if ((this._out_date != value))
				{
					this.Onout_dateChanging(value);
					this.SendPropertyChanging();
					this._out_date = value;
					this.SendPropertyChanged("out_date");
					this.Onout_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_real_rent", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> real_rent
		{
			get
			{
				return this._real_rent;
			}
			set
			{
				if ((this._real_rent != value))
				{
					this.Onreal_rentChanging(value);
					this.SendPropertyChanging();
					this._real_rent = value;
					this.SendPropertyChanged("real_rent");
					this.Onreal_rentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_real_manage", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> real_manage
		{
			get
			{
				return this._real_manage;
			}
			set
			{
				if ((this._real_manage != value))
				{
					this.Onreal_manageChanging(value);
					this.SendPropertyChanging();
					this._real_manage = value;
					this.SendPropertyChanged("real_manage");
					this.Onreal_manageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guarantee", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> guarantee
		{
			get
			{
				return this._guarantee;
			}
			set
			{
				if ((this._guarantee != value))
				{
					this.OnguaranteeChanging(value);
					this.SendPropertyChanging();
					this._guarantee = value;
					this.SendPropertyChanged("guarantee");
					this.OnguaranteeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_situation", DbType="VarChar(200)")]
		public string situation
		{
			get
			{
				return this._situation;
			}
			set
			{
				if ((this._situation != value))
				{
					this.OnsituationChanging(value);
					this.SendPropertyChanging();
					this._situation = value;
					this.SendPropertyChanged("situation");
					this.OnsituationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classify_property", DbType="VarChar(50)")]
		public string classify_property
		{
			get
			{
				return this._classify_property;
			}
			set
			{
				if ((this._classify_property != value))
				{
					this.Onclassify_propertyChanging(value);
					this.SendPropertyChanging();
					this._classify_property = value;
					this.SendPropertyChanged("classify_property");
					this.Onclassify_propertyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_quit", DbType="Bit")]
		public System.Nullable<bool> is_quit
		{
			get
			{
				return this._is_quit;
			}
			set
			{
				if ((this._is_quit != value))
				{
					this.Onis_quitChanging(value);
					this.SendPropertyChanging();
					this._is_quit = value;
					this.SendPropertyChanged("is_quit");
					this.Onis_quitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_not_to_salary", DbType="Bit")]
		public System.Nullable<bool> not_to_salary
		{
			get
			{
				return this._not_to_salary;
			}
			set
			{
				if ((this._not_to_salary != value))
				{
					this.Onnot_to_salaryChanging(value);
					this.SendPropertyChanging();
					this._not_to_salary = value;
					this.SendPropertyChanged("not_to_salary");
					this.Onnot_to_salaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dormitory_dorm_dormitory_lodging", Storage="_dormitory_dorm", ThisKey="dorm_id", OtherKey="id", IsForeignKey=true)]
		public dormitory_dorm dormitory_dorm
		{
			get
			{
				return this._dormitory_dorm.Entity;
			}
			set
			{
				dormitory_dorm previousValue = this._dormitory_dorm.Entity;
				if (((previousValue != value) 
							|| (this._dormitory_dorm.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dormitory_dorm.Entity = null;
						previousValue.dormitory_lodging.Remove(this);
					}
					this._dormitory_dorm.Entity = value;
					if ((value != null))
					{
						value.dormitory_lodging.Add(this);
						this._dorm_id = value.id;
					}
					else
					{
						this._dorm_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("dormitory_dorm");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dormitory_employee_dormitory_lodging", Storage="_dormitory_employee", ThisKey="emp_id", OtherKey="id", IsForeignKey=true)]
		public dormitory_employee dormitory_employee
		{
			get
			{
				return this._dormitory_employee.Entity;
			}
			set
			{
				dormitory_employee previousValue = this._dormitory_employee.Entity;
				if (((previousValue != value) 
							|| (this._dormitory_employee.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dormitory_employee.Entity = null;
						previousValue.dormitory_lodging.Remove(this);
					}
					this._dormitory_employee.Entity = value;
					if ((value != null))
					{
						value.dormitory_lodging.Add(this);
						this._emp_id = value.id;
					}
					else
					{
						this._emp_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("dormitory_employee");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dormitory_other_fee")]
	public partial class dormitory_other_fee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _emp_id;
		
		private System.Nullable<int> _dorm_id;
		
		private string _year_month;
		
		private System.Nullable<decimal> _repair_cost;
		
		private System.Nullable<decimal> _fine;
		
		private System.Nullable<decimal> _guesthouse_cost;
		
		private System.Nullable<decimal> _other_cost;
		
		private System.Nullable<decimal> _out_share_water;
		
		private System.Nullable<decimal> _out_share_eletricity;
		
		private string _comment;
		
		private System.Nullable<System.DateTime> _date;
		
		private EntityRef<dormitory_dorm> _dormitory_dorm;
		
		private EntityRef<dormitory_employee> _dormitory_employee;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onemp_idChanging(System.Nullable<int> value);
    partial void Onemp_idChanged();
    partial void Ondorm_idChanging(System.Nullable<int> value);
    partial void Ondorm_idChanged();
    partial void Onyear_monthChanging(string value);
    partial void Onyear_monthChanged();
    partial void Onrepair_costChanging(System.Nullable<decimal> value);
    partial void Onrepair_costChanged();
    partial void OnfineChanging(System.Nullable<decimal> value);
    partial void OnfineChanged();
    partial void Onguesthouse_costChanging(System.Nullable<decimal> value);
    partial void Onguesthouse_costChanged();
    partial void Onother_costChanging(System.Nullable<decimal> value);
    partial void Onother_costChanged();
    partial void Onout_share_waterChanging(System.Nullable<decimal> value);
    partial void Onout_share_waterChanged();
    partial void Onout_share_eletricityChanging(System.Nullable<decimal> value);
    partial void Onout_share_eletricityChanged();
    partial void OncommentChanging(string value);
    partial void OncommentChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    #endregion
		
		public dormitory_other_fee()
		{
			this._dormitory_dorm = default(EntityRef<dormitory_dorm>);
			this._dormitory_employee = default(EntityRef<dormitory_employee>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_id", DbType="Int")]
		public System.Nullable<int> emp_id
		{
			get
			{
				return this._emp_id;
			}
			set
			{
				if ((this._emp_id != value))
				{
					if (this._dormitory_employee.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onemp_idChanging(value);
					this.SendPropertyChanging();
					this._emp_id = value;
					this.SendPropertyChanged("emp_id");
					this.Onemp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dorm_id", DbType="Int")]
		public System.Nullable<int> dorm_id
		{
			get
			{
				return this._dorm_id;
			}
			set
			{
				if ((this._dorm_id != value))
				{
					if (this._dormitory_dorm.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondorm_idChanging(value);
					this.SendPropertyChanging();
					this._dorm_id = value;
					this.SendPropertyChanged("dorm_id");
					this.Ondorm_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year_month", DbType="VarChar(50)")]
		public string year_month
		{
			get
			{
				return this._year_month;
			}
			set
			{
				if ((this._year_month != value))
				{
					this.Onyear_monthChanging(value);
					this.SendPropertyChanging();
					this._year_month = value;
					this.SendPropertyChanged("year_month");
					this.Onyear_monthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_repair_cost", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> repair_cost
		{
			get
			{
				return this._repair_cost;
			}
			set
			{
				if ((this._repair_cost != value))
				{
					this.Onrepair_costChanging(value);
					this.SendPropertyChanging();
					this._repair_cost = value;
					this.SendPropertyChanged("repair_cost");
					this.Onrepair_costChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fine", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> fine
		{
			get
			{
				return this._fine;
			}
			set
			{
				if ((this._fine != value))
				{
					this.OnfineChanging(value);
					this.SendPropertyChanging();
					this._fine = value;
					this.SendPropertyChanged("fine");
					this.OnfineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guesthouse_cost", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> guesthouse_cost
		{
			get
			{
				return this._guesthouse_cost;
			}
			set
			{
				if ((this._guesthouse_cost != value))
				{
					this.Onguesthouse_costChanging(value);
					this.SendPropertyChanging();
					this._guesthouse_cost = value;
					this.SendPropertyChanged("guesthouse_cost");
					this.Onguesthouse_costChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_other_cost", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> other_cost
		{
			get
			{
				return this._other_cost;
			}
			set
			{
				if ((this._other_cost != value))
				{
					this.Onother_costChanging(value);
					this.SendPropertyChanging();
					this._other_cost = value;
					this.SendPropertyChanged("other_cost");
					this.Onother_costChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_out_share_water", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> out_share_water
		{
			get
			{
				return this._out_share_water;
			}
			set
			{
				if ((this._out_share_water != value))
				{
					this.Onout_share_waterChanging(value);
					this.SendPropertyChanging();
					this._out_share_water = value;
					this.SendPropertyChanged("out_share_water");
					this.Onout_share_waterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_out_share_eletricity", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> out_share_eletricity
		{
			get
			{
				return this._out_share_eletricity;
			}
			set
			{
				if ((this._out_share_eletricity != value))
				{
					this.Onout_share_eletricityChanging(value);
					this.SendPropertyChanging();
					this._out_share_eletricity = value;
					this.SendPropertyChanged("out_share_eletricity");
					this.Onout_share_eletricityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="VarChar(200)")]
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				if ((this._comment != value))
				{
					this.OncommentChanging(value);
					this.SendPropertyChanging();
					this._comment = value;
					this.SendPropertyChanged("comment");
					this.OncommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dormitory_dorm_dormitory_other_fee", Storage="_dormitory_dorm", ThisKey="dorm_id", OtherKey="id", IsForeignKey=true)]
		public dormitory_dorm dormitory_dorm
		{
			get
			{
				return this._dormitory_dorm.Entity;
			}
			set
			{
				dormitory_dorm previousValue = this._dormitory_dorm.Entity;
				if (((previousValue != value) 
							|| (this._dormitory_dorm.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dormitory_dorm.Entity = null;
						previousValue.dormitory_other_fee.Remove(this);
					}
					this._dormitory_dorm.Entity = value;
					if ((value != null))
					{
						value.dormitory_other_fee.Add(this);
						this._dorm_id = value.id;
					}
					else
					{
						this._dorm_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("dormitory_dorm");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dormitory_employee_dormitory_other_fee", Storage="_dormitory_employee", ThisKey="emp_id", OtherKey="id", IsForeignKey=true)]
		public dormitory_employee dormitory_employee
		{
			get
			{
				return this._dormitory_employee.Entity;
			}
			set
			{
				dormitory_employee previousValue = this._dormitory_employee.Entity;
				if (((previousValue != value) 
							|| (this._dormitory_employee.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dormitory_employee.Entity = null;
						previousValue.dormitory_other_fee.Remove(this);
					}
					this._dormitory_employee.Entity = value;
					if ((value != null))
					{
						value.dormitory_other_fee.Add(this);
						this._emp_id = value.id;
					}
					else
					{
						this._emp_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("dormitory_employee");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dormitory_type")]
	public partial class dormitory_type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private System.Nullable<double> _area;
		
		private System.Nullable<decimal> _rent;
		
		private System.Nullable<decimal> _manage_cost;
		
		private string _charge_mode;
		
		private System.Nullable<short> _max_number;
		
		private System.Nullable<System.DateTime> _date;
		
		private EntitySet<dormitory_dorm> _dormitory_dorm;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnareaChanging(System.Nullable<double> value);
    partial void OnareaChanged();
    partial void OnrentChanging(System.Nullable<decimal> value);
    partial void OnrentChanged();
    partial void Onmanage_costChanging(System.Nullable<decimal> value);
    partial void Onmanage_costChanged();
    partial void Oncharge_modeChanging(string value);
    partial void Oncharge_modeChanged();
    partial void Onmax_numberChanging(System.Nullable<short> value);
    partial void Onmax_numberChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    #endregion
		
		public dormitory_type()
		{
			this._dormitory_dorm = new EntitySet<dormitory_dorm>(new Action<dormitory_dorm>(this.attach_dormitory_dorm), new Action<dormitory_dorm>(this.detach_dormitory_dorm));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(20)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area", DbType="Float")]
		public System.Nullable<double> area
		{
			get
			{
				return this._area;
			}
			set
			{
				if ((this._area != value))
				{
					this.OnareaChanging(value);
					this.SendPropertyChanging();
					this._area = value;
					this.SendPropertyChanged("area");
					this.OnareaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rent", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> rent
		{
			get
			{
				return this._rent;
			}
			set
			{
				if ((this._rent != value))
				{
					this.OnrentChanging(value);
					this.SendPropertyChanging();
					this._rent = value;
					this.SendPropertyChanged("rent");
					this.OnrentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manage_cost", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> manage_cost
		{
			get
			{
				return this._manage_cost;
			}
			set
			{
				if ((this._manage_cost != value))
				{
					this.Onmanage_costChanging(value);
					this.SendPropertyChanging();
					this._manage_cost = value;
					this.SendPropertyChanged("manage_cost");
					this.Onmanage_costChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_charge_mode", DbType="VarChar(20)")]
		public string charge_mode
		{
			get
			{
				return this._charge_mode;
			}
			set
			{
				if ((this._charge_mode != value))
				{
					this.Oncharge_modeChanging(value);
					this.SendPropertyChanging();
					this._charge_mode = value;
					this.SendPropertyChanged("charge_mode");
					this.Oncharge_modeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max_number", DbType="SmallInt")]
		public System.Nullable<short> max_number
		{
			get
			{
				return this._max_number;
			}
			set
			{
				if ((this._max_number != value))
				{
					this.Onmax_numberChanging(value);
					this.SendPropertyChanging();
					this._max_number = value;
					this.SendPropertyChanged("max_number");
					this.Onmax_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dormitory_type_dormitory_dorm", Storage="_dormitory_dorm", ThisKey="id", OtherKey="type_id")]
		public EntitySet<dormitory_dorm> dormitory_dorm
		{
			get
			{
				return this._dormitory_dorm;
			}
			set
			{
				this._dormitory_dorm.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_dormitory_dorm(dormitory_dorm entity)
		{
			this.SendPropertyChanging();
			entity.dormitory_type = this;
		}
		
		private void detach_dormitory_dorm(dormitory_dorm entity)
		{
			this.SendPropertyChanging();
			entity.dormitory_type = null;
		}
	}
}
#pragma warning restore 1591
