//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ei_authority
    {
        public ei_authority()
        {
            this.ei_groupAuthority = new HashSet<ei_groupAuthority>();
        }
    
        public int id { get; set; }
        public Nullable<decimal> number { get; set; }
        public string name { get; set; }
        public string en_name { get; set; }
        public string description { get; set; }
        public string controler_name { get; set; }
        public string action_name { get; set; }
        public string iconcls { get; set; }
    
        public virtual ICollection<ei_groupAuthority> ei_groupAuthority { get; set; }
    }
}
