//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ei_apApply
    {
        public ei_apApply()
        {
            this.ei_apApplyEntry = new HashSet<ei_apApplyEntry>();
        }
    
        public int id { get; set; }
        public string sys_no { get; set; }
        public string applier_num { get; set; }
        public string applier_name { get; set; }
        public string applier_phone { get; set; }
        public string bus_name { get; set; }
        public string po_number { get; set; }
        public string comment { get; set; }
        public string charger_no { get; set; }
        public string charger_name { get; set; }
        public string controller_no { get; set; }
        public string controller_name { get; set; }
        public string minister_no { get; set; }
        public string minister_name { get; set; }
        public string account { get; set; }
        public string dep_name { get; set; }
        public Nullable<System.DateTime> apply_time { get; set; }
        public string k3_account { get; set; }
    
        public virtual ICollection<ei_apApplyEntry> ei_apApplyEntry { get; set; }
    }
}
