//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ei_ALModifyLog
    {
        public int id { get; set; }
        public string sys_no { get; set; }
        public Nullable<int> user_id { get; set; }
        public string user_name { get; set; }
        public Nullable<System.DateTime> old_begin_date { get; set; }
        public Nullable<System.DateTime> old_end_date { get; set; }
        public Nullable<System.DateTime> new_begin_date { get; set; }
        public Nullable<System.DateTime> new_end_date { get; set; }
        public Nullable<int> old_days { get; set; }
        public Nullable<decimal> old_hours { get; set; }
        public Nullable<int> new_days { get; set; }
        public Nullable<decimal> new_hours { get; set; }
        public Nullable<System.DateTime> op_date { get; set; }
        public string ip { get; set; }
    }
}
