//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ei_bus_place
    {
        public ei_bus_place()
        {
            this.ei_bus_place_detail = new HashSet<ei_bus_place_detail>();
        }
    
        public int id { get; set; }
        public int sort_no { get; set; }
        public string place { get; set; }
        public int area_size { get; set; }
    
        public virtual ICollection<ei_bus_place_detail> ei_bus_place_detail { get; set; }
    }
}
