//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ei_bus_place_detail
    {
        public int id { get; set; }
        public Nullable<int> place_id { get; set; }
        public string floor { get; set; }
        public string dep_name { get; set; }
        public int dep_size { get; set; }
        public string clear_level { get; set; }
        public string dep_plan { get; set; }
        public string usage { get; set; }
        public byte[] pic { get; set; }
        public string pic_name { get; set; }
        public string dep_charger { get; set; }
    
        public virtual ei_bus_place ei_bus_place { get; set; }
    }
}
