//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ei_dormRepair
    {
        public int id { get; set; }
        public string sys_no { get; set; }
        public string applier_num { get; set; }
        public string applier_name { get; set; }
        public string area_name { get; set; }
        public string dorm_num { get; set; }
        public string repair_type { get; set; }
        public Nullable<System.DateTime> repair_time { get; set; }
        public string fee_share_type { get; set; }
        public string fee_share_peple { get; set; }
        public string repair_content { get; set; }
        public string contact_name { get; set; }
        public string contact_phone { get; set; }
        public string contact_short_phone { get; set; }
        public Nullable<System.DateTime> apply_time { get; set; }
        public string accepter_num { get; set; }
        public string accepter_name { get; set; }
        public Nullable<bool> is_accept { get; set; }
        public string accept_comment { get; set; }
        public string accepter_phone { get; set; }
        public string accepter_short_phone { get; set; }
        public Nullable<System.DateTime> confirm_repair_time { get; set; }
        public string repaire_subject { get; set; }
        public Nullable<decimal> charge_fee { get; set; }
        public Nullable<System.DateTime> finish_repair_time { get; set; }
        public Nullable<System.DateTime> applier_confirm_time { get; set; }
        public string applier_evaluation { get; set; }
        public Nullable<int> applier_evaluation_score { get; set; }
        public bool is_outside { get; set; }
        public string emp_id_should_pay { get; set; }
    }
}
