//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ei_departmentAuditNode
    {
        public ei_departmentAuditNode()
        {
            this.ei_departmentAuditUser = new HashSet<ei_departmentAuditUser>();
        }
    
        public int id { get; set; }
        public Nullable<int> FDepartmentId { get; set; }
        public Nullable<bool> FIsCounterSign { get; set; }
        public string FAuditNodeName { get; set; }
    
        public virtual ei_department ei_department { get; set; }
        public virtual ICollection<ei_departmentAuditUser> ei_departmentAuditUser { get; set; }
    }
}
