//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ei_dormRepairIems
    {
        public int id { get; set; }
        public string sys_no { get; set; }
        public int stock_id { get; set; }
        public string stock_name { get; set; }
        public int item_id { get; set; }
        public string item_name { get; set; }
        public int qty { get; set; }
        public decimal price { get; set; }
        public string op_user { get; set; }
        public string item_type { get; set; }
        public int inventory { get; set; }
        public bool is_public_fee { get; set; }
    }
}
