//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ei_epEqUsers
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> eq_dep_id { get; set; }
        public string job_position { get; set; }
    
        public virtual ei_epEqDeps ei_epEqDeps { get; set; }
        public virtual ei_users ei_users { get; set; }
    }
}
