//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ei_fxApplySelfItems
    {
        public int id { get; set; }
        public string sys_no { get; set; }
        public int entry_id { get; set; }
        public string item_name { get; set; }
        public string item_model { get; set; }
        public int in_qty { get; set; }
        public int out_qty { get; set; }
        public string unit_name { get; set; }
        public string comment { get; set; }
    }
}
