//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ei_fxApply
    {
        public int id { get; set; }
        public string sys_no { get; set; }
        public string applier_num { get; set; }
        public string applier_name { get; set; }
        public string applier_phone { get; set; }
        public System.DateTime apply_time { get; set; }
        public string fx_type_name { get; set; }
        public string fx_type_no { get; set; }
        public string fx_process { get; set; }
        public string company { get; set; }
        public string bus_name { get; set; }
        public int total_pack_num { get; set; }
        public string from_addr { get; set; }
        public string to_scope { get; set; }
        public string to_addr { get; set; }
        public string receiver_name { get; set; }
        public string receiver_phone { get; set; }
        public string ex_company { get; set; }
        public string ex_no { get; set; }
        public string reason { get; set; }
        public string comment { get; set; }
        public bool has_attachment { get; set; }
        public bool can_print { get; set; }
        public string auditor_segs { get; set; }
        public string other_segs { get; set; }
        public string cc_users_name { get; set; }
        public string cc_users_num { get; set; }
        public string out_status { get; set; }
        public Nullable<System.DateTime> out_time { get; set; }
        public string out_guard { get; set; }
        public string take_out_people_type { get; set; }
        public string take_out_people_name { get; set; }
        public string take_out_people_phone { get; set; }
        public string take_out_people_code { get; set; }
    }
}
