//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ei_hhApplyEntry
    {
        public int id { get; set; }
        public int hh_id { get; set; }
        public string order_no { get; set; }
        public string moduel { get; set; }
        public Nullable<int> return_qty { get; set; }
        public Nullable<int> real_return_qty { get; set; }
        public string is_on_line { get; set; }
        public Nullable<int> fill_qty { get; set; }
        public Nullable<int> send_qty { get; set; }
        public string sender_name { get; set; }
        public string c_moduel { get; set; }
        public Nullable<int> real_fill_qty { get; set; }
        public Nullable<int> other_qty { get; set; }
    
        public virtual ei_hhApply ei_hhApply { get; set; }
    }
}
