//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ei_mqApply
    {
        public int id { get; set; }
        public string sys_no { get; set; }
        public string applier_num { get; set; }
        public string applier_name { get; set; }
        public Nullable<System.DateTime> apply_time { get; set; }
        public string card_number { get; set; }
        public string name { get; set; }
        public string sex { get; set; }
        public string dep_name { get; set; }
        public string position { get; set; }
        public string education { get; set; }
        public string hometown { get; set; }
        public string account { get; set; }
        public string quit_reason { get; set; }
        public string quit_suggestion { get; set; }
        public string work_evaluation { get; set; }
        public string work_comment { get; set; }
        public string wanna_employ { get; set; }
        public string employ_comment { get; set; }
        public string group_leader_name { get; set; }
        public string group_leader_num { get; set; }
        public string charger_name { get; set; }
        public string charger_num { get; set; }
        public string produce_minister_name { get; set; }
        public string produce_minister_num { get; set; }
        public string salary_clear_way { get; set; }
        public Nullable<System.DateTime> leave_date { get; set; }
        public string group_leader_choise { get; set; }
        public bool group_leader_talked { get; set; }
        public string charger_choise { get; set; }
        public bool charger_talked { get; set; }
        public Nullable<bool> check1 { get; set; }
    }
}
