//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ei_mtApply
    {
        public int id { get; set; }
        public string applier_number { get; set; }
        public string applier_name { get; set; }
        public System.DateTime apply_time { get; set; }
        public int eqInfo_id { get; set; }
        public string accept_member_no { get; set; }
        public string accept_member_name { get; set; }
        public Nullable<System.DateTime> accept_time { get; set; }
        public Nullable<System.DateTime> maintence_begin_time { get; set; }
        public Nullable<System.DateTime> maintence_end_time { get; set; }
        public Nullable<decimal> maintence_hours { get; set; }
        public string member_helping { get; set; }
        public Nullable<System.DateTime> confirm_time { get; set; }
        public string comment { get; set; }
        public string sys_no { get; set; }
        public Nullable<System.DateTime> maintence_time { get; set; }
    }
}
