//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ei_mtEqInfo
    {
        public int id { get; set; }
        public string property_number { get; set; }
        public string equitment_name { get; set; }
        public string equitment_modual { get; set; }
        public string maker { get; set; }
        public string using_status { get; set; }
        public string check_dep { get; set; }
        public string check_list_no { get; set; }
        public string file_no { get; set; }
        public string produce_dep_name { get; set; }
        public int maintenance_cycle { get; set; }
        public string important_level { get; set; }
        public Nullable<System.DateTime> last_maintenance_date { get; set; }
        public Nullable<System.DateTime> next_maintenance_date { get; set; }
        public string maintenance_status { get; set; }
        public string comment { get; set; }
        public string creater_name { get; set; }
        public string creater_number { get; set; }
        public Nullable<int> class_id { get; set; }
        public System.DateTime create_time { get; set; }
    }
}
