//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ei_mtClass
    {
        public int id { get; set; }
        public string class_name { get; set; }
        public string leader_number { get; set; }
        public string leader { get; set; }
        public string member_number { get; set; }
        public string member { get; set; }
        public System.DateTime create_time { get; set; }
    }
}
