//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ei_pushMsg
    {
        public ei_pushMsg()
        {
            this.ei_PushResponse = new HashSet<ei_PushResponse>();
        }
    
        public int id { get; set; }
        public string card_no { get; set; }
        public Nullable<bool> send_to_all { get; set; }
        public string send_title { get; set; }
        public string send_content { get; set; }
        public string task_type { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> send_date { get; set; }
        public Nullable<bool> has_sent { get; set; }
        public Nullable<long> msg_id { get; set; }
    
        public virtual ICollection<ei_PushResponse> ei_PushResponse { get; set; }
    }
}
