//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ei_PPApply
    {
        public int id { get; set; }
        public string sys_no { get; set; }
        public string applier_num { get; set; }
        public string applier_name { get; set; }
        public System.DateTime apply_time { get; set; }
        public string addr { get; set; }
        public string repair_content { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> repair_day { get; set; }
        public string area_name { get; set; }
    }
}
