//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ei_public_fund
    {
        public int id { get; set; }
        public string 公司 { get; set; }
        public string 单位代码 { get; set; }
        public string 个人代码 { get; set; }
        public string 银行个人账号 { get; set; }
        public string 姓名 { get; set; }
        public string 姓名全拼 { get; set; }
        public string 性别 { get; set; }
        public string 固定电话号码 { get; set; }
        public string 手机号码 { get; set; }
        public string 证件类型 { get; set; }
        public string 证件号码 { get; set; }
        public string 出生年月 { get; set; }
        public string 婚姻状况 { get; set; }
        public string 职业 { get; set; }
        public string 职称 { get; set; }
        public string 职务 { get; set; }
        public string 学历 { get; set; }
        public string 邮政编码 { get; set; }
        public string 家庭住址 { get; set; }
        public string 家庭月收入 { get; set; }
        public Nullable<double> 个人缴存基数 { get; set; }
        public Nullable<double> 个人账户状态 { get; set; }
        public Nullable<double> 开户日期 { get; set; }
        public Nullable<double> 个人账户余额 { get; set; }
        public Nullable<double> 个人月缴额 { get; set; }
        public Nullable<double> 单位月缴额 { get; set; }
        public Nullable<double> 销户日期 { get; set; }
        public string 销户原因 { get; set; }
        public string 个人存款账户号码 { get; set; }
        public string 个人存款账户开户名称 { get; set; }
        public string 个人存款账户开户银行代码 { get; set; }
        public Nullable<double> 单位缴存比例 { get; set; }
        public Nullable<double> 个人缴存比例 { get; set; }
        public Nullable<double> 开始缴交年月 { get; set; }
        public Nullable<double> 缴至年月 { get; set; }
        public Nullable<double> 个人账户上年结转余额 { get; set; }
        public Nullable<double> 个人账户当年当归集余额 { get; set; }
        public Nullable<double> 上期积数 { get; set; }
        public string 当前积数 { get; set; }
        public string 最后一次封存时间 { get; set; }
        public Nullable<double> 应缴月份 { get; set; }
    }
}
