//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ei_sjApplyEntry
    {
        public int id { get; set; }
        public Nullable<int> sj_id { get; set; }
        public string card_number { get; set; }
        public string name { get; set; }
        public string sex { get; set; }
        public string education { get; set; }
        public string account { get; set; }
        public string out_dep_name { get; set; }
        public Nullable<int> out_dep_id { get; set; }
        public string out_dep_position { get; set; }
        public Nullable<System.DateTime> out_time { get; set; }
        public string in_dep_name { get; set; }
        public Nullable<int> in_dep_id { get; set; }
        public string in_dep_position { get; set; }
        public Nullable<System.DateTime> in_time { get; set; }
        public Nullable<bool> is_agree { get; set; }
        public string not_agree_name { get; set; }
    
        public virtual ei_sjApply ei_sjApply { get; set; }
    }
}
