//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ei_TIApply
    {
        public ei_TIApply()
        {
            this.ei_TIApplyEntry = new HashSet<ei_TIApplyEntry>();
        }
    
        public int id { get; set; }
        public string sys_no { get; set; }
        public string applier_name { get; set; }
        public string applier_num { get; set; }
        public Nullable<System.DateTime> in_day { get; set; }
        public string in_timespan { get; set; }
        public string ex_company { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> apply_time { get; set; }
    
        public virtual ICollection<ei_TIApplyEntry> ei_TIApplyEntry { get; set; }
    }
}
