//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ei_TIApplyEntry
    {
        public int id { get; set; }
        public Nullable<int> ti_id { get; set; }
        public string car_type { get; set; }
        public string car_no { get; set; }
        public string driver_name { get; set; }
        public string driver_no { get; set; }
        public string t_status { get; set; }
        public Nullable<System.DateTime> in_time { get; set; }
        public Nullable<System.DateTime> out_time { get; set; }
    
        public virtual ei_TIApply ei_TIApply { get; set; }
    }
}
