//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ei_ucApplyEntry
    {
        public int id { get; set; }
        public Nullable<int> uc_id { get; set; }
        public string num { get; set; }
        public string moduel { get; set; }
        public Nullable<decimal> qty { get; set; }
    
        public virtual ei_ucApply ei_ucApply { get; set; }
    }
}
