//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ei_xaApply
    {
        public int id { get; set; }
        public string sys_no { get; set; }
        public string applier_num { get; set; }
        public string applier_name { get; set; }
        public System.DateTime apply_time { get; set; }
        public string project_name { get; set; }
        public string dept_name { get; set; }
        public string addr { get; set; }
        public string bill_no { get; set; }
        public string classification { get; set; }
        public string project_type { get; set; }
        public string project_detail { get; set; }
        public string reason { get; set; }
        public string demands { get; set; }
        public string save_people { get; set; }
        public string productivity_profit { get; set; }
        public string other_profit { get; set; }
        public bool has_profit { get; set; }
        public string profit_confirm_people_name { get; set; }
        public string profit_confirm_people_num { get; set; }
        public string equitment_auditor_name { get; set; }
        public string equitment_auditor_num { get; set; }
        public string dept_charger_name { get; set; }
        public string dept_charger_num { get; set; }
        public bool can_print { get; set; }
        public Nullable<System.DateTime> check_date { get; set; }
        public string company { get; set; }
        public string applier_phone { get; set; }
        public bool is_share_fee { get; set; }
        public string share_fee_detail { get; set; }
        public string share_fee_managers { get; set; }
        public Nullable<bool> is_po { get; set; }
        public Nullable<System.DateTime> confirm_date { get; set; }
        public string dept_manager_name { get; set; }
        public string dept_manager_num { get; set; }
        public string email_addr { get; set; }
        public string po_no { get; set; }
        public string done_before_apply { get; set; }
        public string has_done_supplier { get; set; }
    }
}
