//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ei_xdApply
    {
        public int id { get; set; }
        public string sys_no { get; set; }
        public string applier_num { get; set; }
        public string applier_name { get; set; }
        public System.DateTime apply_time { get; set; }
        public string pro_type { get; set; }
        public System.DateTime time_from { get; set; }
        public System.DateTime time_to { get; set; }
        public string k3_account { get; set; }
        public string order_no { get; set; }
        public string process_dep { get; set; }
        public string supplier_name { get; set; }
        public int cardborad_num { get; set; }
        public string lod_confirm_people_num { get; set; }
        public string lod_confirm_people { get; set; }
        public string stock_confirm_people_num { get; set; }
        public string stock_confirm_people { get; set; }
        public string reason { get; set; }
        public string dep_charger_num { get; set; }
        public string dep_charger { get; set; }
    }
}
