//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class flow_apply
    {
        public flow_apply()
        {
            this.flow_applyEntry = new HashSet<flow_applyEntry>();
        }
    
        public int id { get; set; }
        public Nullable<int> flow_template_id { get; set; }
        public string create_user { get; set; }
        public Nullable<bool> success { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> finish_date { get; set; }
        public string sys_no { get; set; }
        public string form_title { get; set; }
        public string form_sub_title { get; set; }
        public Nullable<bool> user_abort { get; set; }
    
        public virtual ICollection<flow_applyEntry> flow_applyEntry { get; set; }
        public virtual flow_template flow_template { get; set; }
    }
}
