//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class flow_templateEntry
    {
        public flow_templateEntry()
        {
            this.flow_applyEntry = new HashSet<flow_applyEntry>();
        }
    
        public int id { get; set; }
        public Nullable<int> flow_id { get; set; }
        public Nullable<int> step { get; set; }
        public string step_name { get; set; }
        public string auditors { get; set; }
        public bool can_be_null { get; set; }
        public bool countersign { get; set; }
        public string pass_callback { get; set; }
        public string ng_callback { get; set; }
    
        public virtual ICollection<flow_applyEntry> flow_applyEntry { get; set; }
        public virtual flow_template flow_template { get; set; }
    }
}
