//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class k3_database
    {
        public int id { get; set; }
        public string account_name { get; set; }
        public string server_ip { get; set; }
        public string database_name { get; set; }
        public string po_brand { get; set; }
    }
}
