//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kw_items
    {
        public int id { get; set; }
        public string caption { get; set; }
        public string text_content { get; set; }
        public string catalog { get; set; }
        public string creater_no { get; set; }
        public string creater_name { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> last_update_time { get; set; }
        public string users_can_update { get; set; }
        public bool open_flag { get; set; }
        public Nullable<bool> has_attachment { get; set; }
        public string item_no { get; set; }
        public string item_keys { get; set; }
    }
}
