//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_UserConfig
    {
        public int FID { get; set; }
        public string FNumber { get; set; }
        public string FPhone { get; set; }
        public string FPassword { get; set; }
        public decimal FQuota { get; set; }
        public string FStatus { get; set; }
    }
}
