//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_APExcel
    {
        public int ap_id { get; set; }
        public string sys_no { get; set; }
        public string applier_name { get; set; }
        public string account { get; set; }
        public string bus_name { get; set; }
        public string dep_name { get; set; }
        public Nullable<System.DateTime> apply_time { get; set; }
        public string po_number { get; set; }
        public string k3_account { get; set; }
        public int entry_id { get; set; }
        public string item_no { get; set; }
        public string item_name { get; set; }
        public string item_modual { get; set; }
        public Nullable<int> item_id { get; set; }
        public string brand { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> real_qty { get; set; }
        public string unit_name { get; set; }
        public Nullable<System.DateTime> latest_arrive_date { get; set; }
        public string using_speed { get; set; }
        public string order_period { get; set; }
        public string usage { get; set; }
        public Nullable<int> entry_no { get; set; }
        public string audit_result { get; set; }
    }
}
