//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_assistantEmps
    {
        public string emp_type { get; set; }
        public string dept_name { get; set; }
        public System.DateTime sx_date { get; set; }
        public string rm_date { get; set; }
        public string emp_no1 { get; set; }
        public string emp_no { get; set; }
        public string emp_name { get; set; }
        public string emp_zw { get; set; }
        public string emp_zj { get; set; }
        public string gz_fw { get; set; }
        public string work_name { get; set; }
        public string pay_type { get; set; }
        public string rem { get; set; }
    }
}
