//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_dormEmptyRoom
    {
        public string area_name { get; set; }
        public string dorm_type { get; set; }
        public Nullable<int> room_num { get; set; }
        public int living_room_num { get; set; }
        public decimal manage_cost { get; set; }
    }
}
