//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ep_dep
    {
        public string eq_dep_name { get; set; }
        public string eq_charger_name { get; set; }
        public string eq_charger_number { get; set; }
        public string pr_dep_name { get; set; }
        public string bus_dep_name { get; set; }
        public string pr_charger_name { get; set; }
        public string pr_charger_num { get; set; }
        public int pr_id { get; set; }
    }
}
