//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_KSExcel
    {
        public int id { get; set; }
        public string sys_no { get; set; }
        public string applier_name { get; set; }
        public string applier_number { get; set; }
        public Nullable<System.DateTime> apply_time { get; set; }
        public string dep_name { get; set; }
        public string applier_phone { get; set; }
        public string situation { get; set; }
        public string suggestion { get; set; }
        public string benefit { get; set; }
        public Nullable<int> applier_reward { get; set; }
        public string level_name { get; set; }
        public Nullable<int> level_reward { get; set; }
        public string executor_name { get; set; }
        public string executor_number { get; set; }
        public string group_members { get; set; }
        public string result_description { get; set; }
        public bool has_attachment { get; set; }
        public string operation_dep_opinion { get; set; }
        public string operation_dep_summary { get; set; }
        public string audit_result { get; set; }
    }
}
