//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_leaving_days
    {
        public int id { get; set; }
        public string applier_num { get; set; }
        public string applier_name { get; set; }
        public string leave_type { get; set; }
        public Nullable<System.DateTime> from_date { get; set; }
        public Nullable<System.DateTime> to_date { get; set; }
        public Nullable<int> work_days { get; set; }
        public Nullable<decimal> work_hours { get; set; }
        public Nullable<System.DateTime> apply_time { get; set; }
        public string sys_no { get; set; }
    }
}
