//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_push_users
    {
        public int id { get; set; }
        public string card_number { get; set; }
        public Nullable<int> salary_no { get; set; }
        public string name { get; set; }
        public string wx_openid { get; set; }
        public Nullable<bool> wx_push_salary_info { get; set; }
        public Nullable<bool> wx_push_consume_info { get; set; }
        public Nullable<bool> wx_push_flow_info { get; set; }
        public Nullable<bool> wx_check_salary_info { get; set; }
    }
}
