//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SPReport
    {
        public string sys_no { get; set; }
        public string applier_name { get; set; }
        public string applier_phone { get; set; }
        public string apply_reason { get; set; }
        public Nullable<System.DateTime> apply_time { get; set; }
        public string bus_name { get; set; }
        public Nullable<bool> can_print { get; set; }
        public Nullable<int> cardboard_num { get; set; }
        public string company { get; set; }
        public Nullable<int> package_num { get; set; }
        public int id { get; set; }
        public string name { get; set; }
        public string modual { get; set; }
        public Nullable<int> qty { get; set; }
        public string bus_auditor { get; set; }
        public string administration_auditor { get; set; }
        public string to_addr { get; set; }
    }
}
