//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TIExcel
    {
        public int id { get; set; }
        public string sys_no { get; set; }
        public string applier_name { get; set; }
        public string applier_num { get; set; }
        public Nullable<System.DateTime> in_day { get; set; }
        public string in_timespan { get; set; }
        public string ex_company { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> apply_time { get; set; }
        public int entry_id { get; set; }
        public string driver_name { get; set; }
        public string driver_no { get; set; }
        public string car_no { get; set; }
        public string car_type { get; set; }
        public string t_status { get; set; }
        public Nullable<System.DateTime> in_time { get; set; }
        public Nullable<System.DateTime> out_time { get; set; }
        public string audit_result { get; set; }
    }
}
