//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_pushMsg
    {
        public int id { get; set; }
        public string FPushType { get; set; }
        public string FOpenId { get; set; }
        public string FCardNumber { get; set; }
        public Nullable<System.DateTime> FInTime { get; set; }
        public Nullable<bool> FHasSend { get; set; }
        public Nullable<System.DateTime> FPushTime { get; set; }
        public string FPushResult { get; set; }
        public string FFirst { get; set; }
        public string FkeyWord1 { get; set; }
        public string FKeyWord2 { get; set; }
        public string FKeyWord3 { get; set; }
        public string FKeyWord4 { get; set; }
        public string FKeyWord5 { get; set; }
        public string FKeyWord6 { get; set; }
        public string FKeyWord7 { get; set; }
        public string FKeyWord8 { get; set; }
        public string FRemark { get; set; }
        public string FUrl { get; set; }
    }
}
