//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.FlowSvr {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlowResultModel", Namespace="http://ic.truly.com.cn/")]
    [System.SerializableAttribute()]
    public partial class FlowResultModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool sucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nextAuditorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool suc {
            get {
                return this.sucField;
            }
            set {
                if ((this.sucField.Equals(value) != true)) {
                    this.sucField = value;
                    this.RaisePropertyChanged("suc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                if ((object.ReferenceEquals(this.msgField, value) != true)) {
                    this.msgField = value;
                    this.RaisePropertyChanged("msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nextAuditors {
            get {
                return this.nextAuditorsField;
            }
            set {
                if ((object.ReferenceEquals(this.nextAuditorsField, value) != true)) {
                    this.nextAuditorsField = value;
                    this.RaisePropertyChanged("nextAuditors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlowRecordModels", Namespace="http://ic.truly.com.cn/")]
    [System.SerializableAttribute()]
    public partial class FlowRecordModels : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> stepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stepNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string auditorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string auditTimesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string auditResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string opinionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> step {
            get {
                return this.stepField;
            }
            set {
                if ((this.stepField.Equals(value) != true)) {
                    this.stepField = value;
                    this.RaisePropertyChanged("step");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string stepName {
            get {
                return this.stepNameField;
            }
            set {
                if ((object.ReferenceEquals(this.stepNameField, value) != true)) {
                    this.stepNameField = value;
                    this.RaisePropertyChanged("stepName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string auditors {
            get {
                return this.auditorsField;
            }
            set {
                if ((object.ReferenceEquals(this.auditorsField, value) != true)) {
                    this.auditorsField = value;
                    this.RaisePropertyChanged("auditors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string auditTimes {
            get {
                return this.auditTimesField;
            }
            set {
                if ((object.ReferenceEquals(this.auditTimesField, value) != true)) {
                    this.auditTimesField = value;
                    this.RaisePropertyChanged("auditTimes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string auditResult {
            get {
                return this.auditResultField;
            }
            set {
                if ((object.ReferenceEquals(this.auditResultField, value) != true)) {
                    this.auditResultField = value;
                    this.RaisePropertyChanged("auditResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string opinions {
            get {
                return this.opinionsField;
            }
            set {
                if ((object.ReferenceEquals(this.opinionsField, value) != true)) {
                    this.opinionsField = value;
                    this.RaisePropertyChanged("opinions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://ic.truly.com.cn/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlowMyAppliesModel", Namespace="http://ic.truly.com.cn/")]
    [System.SerializableAttribute()]
    public partial class FlowMyAppliesModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<System.DateTime> applyTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sysNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string billTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string auditResultField;
        
        private System.Nullable<System.DateTime> finishTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> applyTime {
            get {
                return this.applyTimeField;
            }
            set {
                if ((this.applyTimeField.Equals(value) != true)) {
                    this.applyTimeField = value;
                    this.RaisePropertyChanged("applyTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sysNo {
            get {
                return this.sysNoField;
            }
            set {
                if ((object.ReferenceEquals(this.sysNoField, value) != true)) {
                    this.sysNoField = value;
                    this.RaisePropertyChanged("sysNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string subTitle {
            get {
                return this.subTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.subTitleField, value) != true)) {
                    this.subTitleField = value;
                    this.RaisePropertyChanged("subTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string billType {
            get {
                return this.billTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.billTypeField, value) != true)) {
                    this.billTypeField = value;
                    this.RaisePropertyChanged("billType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string auditResult {
            get {
                return this.auditResultField;
            }
            set {
                if ((object.ReferenceEquals(this.auditResultField, value) != true)) {
                    this.auditResultField = value;
                    this.RaisePropertyChanged("auditResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<System.DateTime> finishTime {
            get {
                return this.finishTimeField;
            }
            set {
                if ((this.finishTimeField.Equals(value) != true)) {
                    this.finishTimeField = value;
                    this.RaisePropertyChanged("finishTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://ic.truly.com.cn/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlowAuditListModel", Namespace="http://ic.truly.com.cn/")]
    [System.SerializableAttribute()]
    public partial class FlowAuditListModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<System.DateTime> applyTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sysNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string billTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string applierField;
        
        private System.Nullable<int> stepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stepNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string auditResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string finalResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> applyTime {
            get {
                return this.applyTimeField;
            }
            set {
                if ((this.applyTimeField.Equals(value) != true)) {
                    this.applyTimeField = value;
                    this.RaisePropertyChanged("applyTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sysNo {
            get {
                return this.sysNoField;
            }
            set {
                if ((object.ReferenceEquals(this.sysNoField, value) != true)) {
                    this.sysNoField = value;
                    this.RaisePropertyChanged("sysNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string billType {
            get {
                return this.billTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.billTypeField, value) != true)) {
                    this.billTypeField = value;
                    this.RaisePropertyChanged("billType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string subTitle {
            get {
                return this.subTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.subTitleField, value) != true)) {
                    this.subTitleField = value;
                    this.RaisePropertyChanged("subTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string applier {
            get {
                return this.applierField;
            }
            set {
                if ((object.ReferenceEquals(this.applierField, value) != true)) {
                    this.applierField = value;
                    this.RaisePropertyChanged("applier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> step {
            get {
                return this.stepField;
            }
            set {
                if ((this.stepField.Equals(value) != true)) {
                    this.stepField = value;
                    this.RaisePropertyChanged("step");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string stepName {
            get {
                return this.stepNameField;
            }
            set {
                if ((object.ReferenceEquals(this.stepNameField, value) != true)) {
                    this.stepNameField = value;
                    this.RaisePropertyChanged("stepName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string auditResult {
            get {
                return this.auditResultField;
            }
            set {
                if ((object.ReferenceEquals(this.auditResultField, value) != true)) {
                    this.auditResultField = value;
                    this.RaisePropertyChanged("auditResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string finalResult {
            get {
                return this.finalResultField;
            }
            set {
                if ((object.ReferenceEquals(this.finalResultField, value) != true)) {
                    this.finalResultField = value;
                    this.RaisePropertyChanged("finalResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CurrentAuditModel", Namespace="http://ic.truly.com.cn/")]
    [System.SerializableAttribute()]
    public partial class CurrentAuditModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int stepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stepNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string auditorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int step {
            get {
                return this.stepField;
            }
            set {
                if ((this.stepField.Equals(value) != true)) {
                    this.stepField = value;
                    this.RaisePropertyChanged("step");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string stepName {
            get {
                return this.stepNameField;
            }
            set {
                if ((object.ReferenceEquals(this.stepNameField, value) != true)) {
                    this.stepNameField = value;
                    this.RaisePropertyChanged("stepName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string auditors {
            get {
                return this.auditorsField;
            }
            set {
                if ((object.ReferenceEquals(this.auditorsField, value) != true)) {
                    this.auditorsField = value;
                    this.RaisePropertyChanged("auditors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ic.truly.com.cn/", ConfigurationName="FlowSvr.FlowSvrSoap")]
    public interface FlowSvrSoap {
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 formJson 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/StartWorkFlow", ReplyAction="*")]
        EmpInfo.FlowSvr.StartWorkFlowResponse StartWorkFlow(EmpInfo.FlowSvr.StartWorkFlowRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 sysNo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/BeginAudit", ReplyAction="*")]
        EmpInfo.FlowSvr.BeginAuditResponse BeginAudit(EmpInfo.FlowSvr.BeginAuditRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 sysNo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/GetApplyResult", ReplyAction="*")]
        EmpInfo.FlowSvr.GetApplyResultResponse GetApplyResult(EmpInfo.FlowSvr.GetApplyResultRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 sysNo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/GetFlowRecord", ReplyAction="*")]
        EmpInfo.FlowSvr.GetFlowRecordResponse GetFlowRecord(EmpInfo.FlowSvr.GetFlowRecordRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 applier 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/GetMyApplyList", ReplyAction="*")]
        EmpInfo.FlowSvr.GetMyApplyListResponse GetMyApplyList(EmpInfo.FlowSvr.GetMyApplyListRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 auditor 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/GetAuditList", ReplyAction="*")]
        EmpInfo.FlowSvr.GetAuditListResponse GetAuditList(EmpInfo.FlowSvr.GetAuditListRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 applier 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/GetMyApplyCount", ReplyAction="*")]
        EmpInfo.FlowSvr.GetMyApplyCountResponse GetMyApplyCount(EmpInfo.FlowSvr.GetMyApplyCountRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 auditor 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/GetMyDealingApplyCount", ReplyAction="*")]
        EmpInfo.FlowSvr.GetMyDealingApplyCountResponse GetMyDealingApplyCount(EmpInfo.FlowSvr.GetMyDealingApplyCountRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 sysNo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/GetCurrentStep", ReplyAction="*")]
        EmpInfo.FlowSvr.GetCurrentStepResponse GetCurrentStep(EmpInfo.FlowSvr.GetCurrentStepRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 userNumber 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/AbortFlow", ReplyAction="*")]
        EmpInfo.FlowSvr.AbortFlowResponse AbortFlow(EmpInfo.FlowSvr.AbortFlowRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 TestStarFlowResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/TestStarFlow", ReplyAction="*")]
        EmpInfo.FlowSvr.TestStarFlowResponse TestStarFlow(EmpInfo.FlowSvr.TestStarFlowRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 TestAuditResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/TestAudit", ReplyAction="*")]
        EmpInfo.FlowSvr.TestAuditResponse TestAudit(EmpInfo.FlowSvr.TestAuditRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 sysNo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/TestFlowRecord", ReplyAction="*")]
        EmpInfo.FlowSvr.TestFlowRecordResponse TestFlowRecord(EmpInfo.FlowSvr.TestFlowRecordRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 sysNo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/TestFlowAuditList", ReplyAction="*")]
        EmpInfo.FlowSvr.TestFlowAuditListResponse TestFlowAuditList(EmpInfo.FlowSvr.TestFlowAuditListRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 TestMyFlowListResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/TestMyFlowList", ReplyAction="*")]
        EmpInfo.FlowSvr.TestMyFlowListResponse TestMyFlowList(EmpInfo.FlowSvr.TestMyFlowListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartWorkFlowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartWorkFlow", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.StartWorkFlowRequestBody Body;
        
        public StartWorkFlowRequest() {
        }
        
        public StartWorkFlowRequest(EmpInfo.FlowSvr.StartWorkFlowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class StartWorkFlowRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string formJson;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string billType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string createUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sysNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string subTitle;
        
        public StartWorkFlowRequestBody() {
        }
        
        public StartWorkFlowRequestBody(string formJson, string billType, string createUser, string sysNo, string title, string subTitle) {
            this.formJson = formJson;
            this.billType = billType;
            this.createUser = createUser;
            this.sysNo = sysNo;
            this.title = title;
            this.subTitle = subTitle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartWorkFlowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartWorkFlowResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.StartWorkFlowResponseBody Body;
        
        public StartWorkFlowResponse() {
        }
        
        public StartWorkFlowResponse(EmpInfo.FlowSvr.StartWorkFlowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class StartWorkFlowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmpInfo.FlowSvr.FlowResultModel StartWorkFlowResult;
        
        public StartWorkFlowResponseBody() {
        }
        
        public StartWorkFlowResponseBody(EmpInfo.FlowSvr.FlowResultModel StartWorkFlowResult) {
            this.StartWorkFlowResult = StartWorkFlowResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BeginAuditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BeginAudit", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.BeginAuditRequestBody Body;
        
        public BeginAuditRequest() {
        }
        
        public BeginAuditRequest(EmpInfo.FlowSvr.BeginAuditRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class BeginAuditRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sysNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int currentStep;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool isPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string opinion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string formJson;
        
        public BeginAuditRequestBody() {
        }
        
        public BeginAuditRequestBody(string sysNo, int currentStep, string userNumber, bool isPass, string opinion, string formJson) {
            this.sysNo = sysNo;
            this.currentStep = currentStep;
            this.userNumber = userNumber;
            this.isPass = isPass;
            this.opinion = opinion;
            this.formJson = formJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BeginAuditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BeginAuditResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.BeginAuditResponseBody Body;
        
        public BeginAuditResponse() {
        }
        
        public BeginAuditResponse(EmpInfo.FlowSvr.BeginAuditResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class BeginAuditResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmpInfo.FlowSvr.FlowResultModel BeginAuditResult;
        
        public BeginAuditResponseBody() {
        }
        
        public BeginAuditResponseBody(EmpInfo.FlowSvr.FlowResultModel BeginAuditResult) {
            this.BeginAuditResult = BeginAuditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetApplyResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetApplyResult", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.GetApplyResultRequestBody Body;
        
        public GetApplyResultRequest() {
        }
        
        public GetApplyResultRequest(EmpInfo.FlowSvr.GetApplyResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetApplyResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sysNo;
        
        public GetApplyResultRequestBody() {
        }
        
        public GetApplyResultRequestBody(string sysNo) {
            this.sysNo = sysNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetApplyResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetApplyResultResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.GetApplyResultResponseBody Body;
        
        public GetApplyResultResponse() {
        }
        
        public GetApplyResultResponse(EmpInfo.FlowSvr.GetApplyResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetApplyResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetApplyResultResult;
        
        public GetApplyResultResponseBody() {
        }
        
        public GetApplyResultResponseBody(string GetApplyResultResult) {
            this.GetApplyResultResult = GetApplyResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFlowRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFlowRecord", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.GetFlowRecordRequestBody Body;
        
        public GetFlowRecordRequest() {
        }
        
        public GetFlowRecordRequest(EmpInfo.FlowSvr.GetFlowRecordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetFlowRecordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sysNo;
        
        public GetFlowRecordRequestBody() {
        }
        
        public GetFlowRecordRequestBody(string sysNo) {
            this.sysNo = sysNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFlowRecordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFlowRecordResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.GetFlowRecordResponseBody Body;
        
        public GetFlowRecordResponse() {
        }
        
        public GetFlowRecordResponse(EmpInfo.FlowSvr.GetFlowRecordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetFlowRecordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmpInfo.FlowSvr.FlowRecordModels[] GetFlowRecordResult;
        
        public GetFlowRecordResponseBody() {
        }
        
        public GetFlowRecordResponseBody(EmpInfo.FlowSvr.FlowRecordModels[] GetFlowRecordResult) {
            this.GetFlowRecordResult = GetFlowRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMyApplyListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMyApplyList", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.GetMyApplyListRequestBody Body;
        
        public GetMyApplyListRequest() {
        }
        
        public GetMyApplyListRequest(EmpInfo.FlowSvr.GetMyApplyListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetMyApplyListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string applier;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fromDateQuery;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string toDateQuery;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sysNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public EmpInfo.FlowSvr.ArrayOfString billType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string subTitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int auditResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int maxReturnCount;
        
        public GetMyApplyListRequestBody() {
        }
        
        public GetMyApplyListRequestBody(string applier, string fromDateQuery, string toDateQuery, string sysNo, EmpInfo.FlowSvr.ArrayOfString billType, string title, string subTitle, int auditResult, int maxReturnCount) {
            this.applier = applier;
            this.fromDateQuery = fromDateQuery;
            this.toDateQuery = toDateQuery;
            this.sysNo = sysNo;
            this.billType = billType;
            this.title = title;
            this.subTitle = subTitle;
            this.auditResult = auditResult;
            this.maxReturnCount = maxReturnCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMyApplyListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMyApplyListResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.GetMyApplyListResponseBody Body;
        
        public GetMyApplyListResponse() {
        }
        
        public GetMyApplyListResponse(EmpInfo.FlowSvr.GetMyApplyListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetMyApplyListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmpInfo.FlowSvr.FlowMyAppliesModel[] GetMyApplyListResult;
        
        public GetMyApplyListResponseBody() {
        }
        
        public GetMyApplyListResponseBody(EmpInfo.FlowSvr.FlowMyAppliesModel[] GetMyApplyListResult) {
            this.GetMyApplyListResult = GetMyApplyListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAuditListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAuditList", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.GetAuditListRequestBody Body;
        
        public GetAuditListRequest() {
        }
        
        public GetAuditListRequest(EmpInfo.FlowSvr.GetAuditListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetAuditListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string auditor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sysNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string applier;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string subTitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string fromTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string toTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public EmpInfo.FlowSvr.ArrayOfInt auditResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public EmpInfo.FlowSvr.ArrayOfInt finalResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public EmpInfo.FlowSvr.ArrayOfString billTypes;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int maxReturnCount;
        
        public GetAuditListRequestBody() {
        }
        
        public GetAuditListRequestBody(string auditor, string sysNo, string applier, string title, string subTitle, string fromTime, string toTime, EmpInfo.FlowSvr.ArrayOfInt auditResult, EmpInfo.FlowSvr.ArrayOfInt finalResult, EmpInfo.FlowSvr.ArrayOfString billTypes, int maxReturnCount) {
            this.auditor = auditor;
            this.sysNo = sysNo;
            this.applier = applier;
            this.title = title;
            this.subTitle = subTitle;
            this.fromTime = fromTime;
            this.toTime = toTime;
            this.auditResult = auditResult;
            this.finalResult = finalResult;
            this.billTypes = billTypes;
            this.maxReturnCount = maxReturnCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAuditListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAuditListResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.GetAuditListResponseBody Body;
        
        public GetAuditListResponse() {
        }
        
        public GetAuditListResponse(EmpInfo.FlowSvr.GetAuditListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetAuditListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmpInfo.FlowSvr.FlowAuditListModel[] GetAuditListResult;
        
        public GetAuditListResponseBody() {
        }
        
        public GetAuditListResponseBody(EmpInfo.FlowSvr.FlowAuditListModel[] GetAuditListResult) {
            this.GetAuditListResult = GetAuditListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMyApplyCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMyApplyCount", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.GetMyApplyCountRequestBody Body;
        
        public GetMyApplyCountRequest() {
        }
        
        public GetMyApplyCountRequest(EmpInfo.FlowSvr.GetMyApplyCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetMyApplyCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string applier;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public EmpInfo.FlowSvr.ArrayOfString billType;
        
        public GetMyApplyCountRequestBody() {
        }
        
        public GetMyApplyCountRequestBody(string applier, EmpInfo.FlowSvr.ArrayOfString billType) {
            this.applier = applier;
            this.billType = billType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMyApplyCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMyApplyCountResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.GetMyApplyCountResponseBody Body;
        
        public GetMyApplyCountResponse() {
        }
        
        public GetMyApplyCountResponse(EmpInfo.FlowSvr.GetMyApplyCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetMyApplyCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetMyApplyCountResult;
        
        public GetMyApplyCountResponseBody() {
        }
        
        public GetMyApplyCountResponseBody(int GetMyApplyCountResult) {
            this.GetMyApplyCountResult = GetMyApplyCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMyDealingApplyCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMyDealingApplyCount", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.GetMyDealingApplyCountRequestBody Body;
        
        public GetMyDealingApplyCountRequest() {
        }
        
        public GetMyDealingApplyCountRequest(EmpInfo.FlowSvr.GetMyDealingApplyCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetMyDealingApplyCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string auditor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public EmpInfo.FlowSvr.ArrayOfString billType;
        
        public GetMyDealingApplyCountRequestBody() {
        }
        
        public GetMyDealingApplyCountRequestBody(string auditor, EmpInfo.FlowSvr.ArrayOfString billType) {
            this.auditor = auditor;
            this.billType = billType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMyDealingApplyCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMyDealingApplyCountResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.GetMyDealingApplyCountResponseBody Body;
        
        public GetMyDealingApplyCountResponse() {
        }
        
        public GetMyDealingApplyCountResponse(EmpInfo.FlowSvr.GetMyDealingApplyCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetMyDealingApplyCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetMyDealingApplyCountResult;
        
        public GetMyDealingApplyCountResponseBody() {
        }
        
        public GetMyDealingApplyCountResponseBody(int GetMyDealingApplyCountResult) {
            this.GetMyDealingApplyCountResult = GetMyDealingApplyCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentStepRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentStep", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.GetCurrentStepRequestBody Body;
        
        public GetCurrentStepRequest() {
        }
        
        public GetCurrentStepRequest(EmpInfo.FlowSvr.GetCurrentStepRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetCurrentStepRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sysNo;
        
        public GetCurrentStepRequestBody() {
        }
        
        public GetCurrentStepRequestBody(string sysNo) {
            this.sysNo = sysNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentStepResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentStepResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.GetCurrentStepResponseBody Body;
        
        public GetCurrentStepResponse() {
        }
        
        public GetCurrentStepResponse(EmpInfo.FlowSvr.GetCurrentStepResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetCurrentStepResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmpInfo.FlowSvr.CurrentAuditModel GetCurrentStepResult;
        
        public GetCurrentStepResponseBody() {
        }
        
        public GetCurrentStepResponseBody(EmpInfo.FlowSvr.CurrentAuditModel GetCurrentStepResult) {
            this.GetCurrentStepResult = GetCurrentStepResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AbortFlowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AbortFlow", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.AbortFlowRequestBody Body;
        
        public AbortFlowRequest() {
        }
        
        public AbortFlowRequest(EmpInfo.FlowSvr.AbortFlowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class AbortFlowRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sysNo;
        
        public AbortFlowRequestBody() {
        }
        
        public AbortFlowRequestBody(string userNumber, string sysNo) {
            this.userNumber = userNumber;
            this.sysNo = sysNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AbortFlowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AbortFlowResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.AbortFlowResponseBody Body;
        
        public AbortFlowResponse() {
        }
        
        public AbortFlowResponse(EmpInfo.FlowSvr.AbortFlowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class AbortFlowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmpInfo.FlowSvr.FlowResultModel AbortFlowResult;
        
        public AbortFlowResponseBody() {
        }
        
        public AbortFlowResponseBody(EmpInfo.FlowSvr.FlowResultModel AbortFlowResult) {
            this.AbortFlowResult = AbortFlowResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestStarFlowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestStarFlow", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.TestStarFlowRequestBody Body;
        
        public TestStarFlowRequest() {
        }
        
        public TestStarFlowRequest(EmpInfo.FlowSvr.TestStarFlowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestStarFlowRequestBody {
        
        public TestStarFlowRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestStarFlowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestStarFlowResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.TestStarFlowResponseBody Body;
        
        public TestStarFlowResponse() {
        }
        
        public TestStarFlowResponse(EmpInfo.FlowSvr.TestStarFlowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class TestStarFlowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmpInfo.FlowSvr.FlowResultModel TestStarFlowResult;
        
        public TestStarFlowResponseBody() {
        }
        
        public TestStarFlowResponseBody(EmpInfo.FlowSvr.FlowResultModel TestStarFlowResult) {
            this.TestStarFlowResult = TestStarFlowResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestAuditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestAudit", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.TestAuditRequestBody Body;
        
        public TestAuditRequest() {
        }
        
        public TestAuditRequest(EmpInfo.FlowSvr.TestAuditRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestAuditRequestBody {
        
        public TestAuditRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestAuditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestAuditResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.TestAuditResponseBody Body;
        
        public TestAuditResponse() {
        }
        
        public TestAuditResponse(EmpInfo.FlowSvr.TestAuditResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class TestAuditResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmpInfo.FlowSvr.FlowResultModel TestAuditResult;
        
        public TestAuditResponseBody() {
        }
        
        public TestAuditResponseBody(EmpInfo.FlowSvr.FlowResultModel TestAuditResult) {
            this.TestAuditResult = TestAuditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestFlowRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestFlowRecord", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.TestFlowRecordRequestBody Body;
        
        public TestFlowRecordRequest() {
        }
        
        public TestFlowRecordRequest(EmpInfo.FlowSvr.TestFlowRecordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class TestFlowRecordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sysNo;
        
        public TestFlowRecordRequestBody() {
        }
        
        public TestFlowRecordRequestBody(string sysNo) {
            this.sysNo = sysNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestFlowRecordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestFlowRecordResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.TestFlowRecordResponseBody Body;
        
        public TestFlowRecordResponse() {
        }
        
        public TestFlowRecordResponse(EmpInfo.FlowSvr.TestFlowRecordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class TestFlowRecordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmpInfo.FlowSvr.FlowRecordModels[] TestFlowRecordResult;
        
        public TestFlowRecordResponseBody() {
        }
        
        public TestFlowRecordResponseBody(EmpInfo.FlowSvr.FlowRecordModels[] TestFlowRecordResult) {
            this.TestFlowRecordResult = TestFlowRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestFlowAuditListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestFlowAuditList", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.TestFlowAuditListRequestBody Body;
        
        public TestFlowAuditListRequest() {
        }
        
        public TestFlowAuditListRequest(EmpInfo.FlowSvr.TestFlowAuditListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class TestFlowAuditListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sysNo;
        
        public TestFlowAuditListRequestBody() {
        }
        
        public TestFlowAuditListRequestBody(string sysNo) {
            this.sysNo = sysNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestFlowAuditListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestFlowAuditListResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.TestFlowAuditListResponseBody Body;
        
        public TestFlowAuditListResponse() {
        }
        
        public TestFlowAuditListResponse(EmpInfo.FlowSvr.TestFlowAuditListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class TestFlowAuditListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmpInfo.FlowSvr.FlowAuditListModel[] TestFlowAuditListResult;
        
        public TestFlowAuditListResponseBody() {
        }
        
        public TestFlowAuditListResponseBody(EmpInfo.FlowSvr.FlowAuditListModel[] TestFlowAuditListResult) {
            this.TestFlowAuditListResult = TestFlowAuditListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestMyFlowListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestMyFlowList", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.TestMyFlowListRequestBody Body;
        
        public TestMyFlowListRequest() {
        }
        
        public TestMyFlowListRequest(EmpInfo.FlowSvr.TestMyFlowListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestMyFlowListRequestBody {
        
        public TestMyFlowListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestMyFlowListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestMyFlowListResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.FlowSvr.TestMyFlowListResponseBody Body;
        
        public TestMyFlowListResponse() {
        }
        
        public TestMyFlowListResponse(EmpInfo.FlowSvr.TestMyFlowListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class TestMyFlowListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmpInfo.FlowSvr.FlowMyAppliesModel[] TestMyFlowListResult;
        
        public TestMyFlowListResponseBody() {
        }
        
        public TestMyFlowListResponseBody(EmpInfo.FlowSvr.FlowMyAppliesModel[] TestMyFlowListResult) {
            this.TestMyFlowListResult = TestMyFlowListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FlowSvrSoapChannel : EmpInfo.FlowSvr.FlowSvrSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FlowSvrSoapClient : System.ServiceModel.ClientBase<EmpInfo.FlowSvr.FlowSvrSoap>, EmpInfo.FlowSvr.FlowSvrSoap {
        
        public FlowSvrSoapClient() {
        }
        
        public FlowSvrSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FlowSvrSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlowSvrSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlowSvrSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.FlowSvr.StartWorkFlowResponse EmpInfo.FlowSvr.FlowSvrSoap.StartWorkFlow(EmpInfo.FlowSvr.StartWorkFlowRequest request) {
            return base.Channel.StartWorkFlow(request);
        }
        
        public EmpInfo.FlowSvr.FlowResultModel StartWorkFlow(string formJson, string billType, string createUser, string sysNo, string title, string subTitle) {
            EmpInfo.FlowSvr.StartWorkFlowRequest inValue = new EmpInfo.FlowSvr.StartWorkFlowRequest();
            inValue.Body = new EmpInfo.FlowSvr.StartWorkFlowRequestBody();
            inValue.Body.formJson = formJson;
            inValue.Body.billType = billType;
            inValue.Body.createUser = createUser;
            inValue.Body.sysNo = sysNo;
            inValue.Body.title = title;
            inValue.Body.subTitle = subTitle;
            EmpInfo.FlowSvr.StartWorkFlowResponse retVal = ((EmpInfo.FlowSvr.FlowSvrSoap)(this)).StartWorkFlow(inValue);
            return retVal.Body.StartWorkFlowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.FlowSvr.BeginAuditResponse EmpInfo.FlowSvr.FlowSvrSoap.BeginAudit(EmpInfo.FlowSvr.BeginAuditRequest request) {
            return base.Channel.BeginAudit(request);
        }
        
        public EmpInfo.FlowSvr.FlowResultModel BeginAudit(string sysNo, int currentStep, string userNumber, bool isPass, string opinion, string formJson) {
            EmpInfo.FlowSvr.BeginAuditRequest inValue = new EmpInfo.FlowSvr.BeginAuditRequest();
            inValue.Body = new EmpInfo.FlowSvr.BeginAuditRequestBody();
            inValue.Body.sysNo = sysNo;
            inValue.Body.currentStep = currentStep;
            inValue.Body.userNumber = userNumber;
            inValue.Body.isPass = isPass;
            inValue.Body.opinion = opinion;
            inValue.Body.formJson = formJson;
            EmpInfo.FlowSvr.BeginAuditResponse retVal = ((EmpInfo.FlowSvr.FlowSvrSoap)(this)).BeginAudit(inValue);
            return retVal.Body.BeginAuditResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.FlowSvr.GetApplyResultResponse EmpInfo.FlowSvr.FlowSvrSoap.GetApplyResult(EmpInfo.FlowSvr.GetApplyResultRequest request) {
            return base.Channel.GetApplyResult(request);
        }
        
        public string GetApplyResult(string sysNo) {
            EmpInfo.FlowSvr.GetApplyResultRequest inValue = new EmpInfo.FlowSvr.GetApplyResultRequest();
            inValue.Body = new EmpInfo.FlowSvr.GetApplyResultRequestBody();
            inValue.Body.sysNo = sysNo;
            EmpInfo.FlowSvr.GetApplyResultResponse retVal = ((EmpInfo.FlowSvr.FlowSvrSoap)(this)).GetApplyResult(inValue);
            return retVal.Body.GetApplyResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.FlowSvr.GetFlowRecordResponse EmpInfo.FlowSvr.FlowSvrSoap.GetFlowRecord(EmpInfo.FlowSvr.GetFlowRecordRequest request) {
            return base.Channel.GetFlowRecord(request);
        }
        
        public EmpInfo.FlowSvr.FlowRecordModels[] GetFlowRecord(string sysNo) {
            EmpInfo.FlowSvr.GetFlowRecordRequest inValue = new EmpInfo.FlowSvr.GetFlowRecordRequest();
            inValue.Body = new EmpInfo.FlowSvr.GetFlowRecordRequestBody();
            inValue.Body.sysNo = sysNo;
            EmpInfo.FlowSvr.GetFlowRecordResponse retVal = ((EmpInfo.FlowSvr.FlowSvrSoap)(this)).GetFlowRecord(inValue);
            return retVal.Body.GetFlowRecordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.FlowSvr.GetMyApplyListResponse EmpInfo.FlowSvr.FlowSvrSoap.GetMyApplyList(EmpInfo.FlowSvr.GetMyApplyListRequest request) {
            return base.Channel.GetMyApplyList(request);
        }
        
        public EmpInfo.FlowSvr.FlowMyAppliesModel[] GetMyApplyList(string applier, string fromDateQuery, string toDateQuery, string sysNo, EmpInfo.FlowSvr.ArrayOfString billType, string title, string subTitle, int auditResult, int maxReturnCount) {
            EmpInfo.FlowSvr.GetMyApplyListRequest inValue = new EmpInfo.FlowSvr.GetMyApplyListRequest();
            inValue.Body = new EmpInfo.FlowSvr.GetMyApplyListRequestBody();
            inValue.Body.applier = applier;
            inValue.Body.fromDateQuery = fromDateQuery;
            inValue.Body.toDateQuery = toDateQuery;
            inValue.Body.sysNo = sysNo;
            inValue.Body.billType = billType;
            inValue.Body.title = title;
            inValue.Body.subTitle = subTitle;
            inValue.Body.auditResult = auditResult;
            inValue.Body.maxReturnCount = maxReturnCount;
            EmpInfo.FlowSvr.GetMyApplyListResponse retVal = ((EmpInfo.FlowSvr.FlowSvrSoap)(this)).GetMyApplyList(inValue);
            return retVal.Body.GetMyApplyListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.FlowSvr.GetAuditListResponse EmpInfo.FlowSvr.FlowSvrSoap.GetAuditList(EmpInfo.FlowSvr.GetAuditListRequest request) {
            return base.Channel.GetAuditList(request);
        }
        
        public EmpInfo.FlowSvr.FlowAuditListModel[] GetAuditList(string auditor, string sysNo, string applier, string title, string subTitle, string fromTime, string toTime, EmpInfo.FlowSvr.ArrayOfInt auditResult, EmpInfo.FlowSvr.ArrayOfInt finalResult, EmpInfo.FlowSvr.ArrayOfString billTypes, int maxReturnCount) {
            EmpInfo.FlowSvr.GetAuditListRequest inValue = new EmpInfo.FlowSvr.GetAuditListRequest();
            inValue.Body = new EmpInfo.FlowSvr.GetAuditListRequestBody();
            inValue.Body.auditor = auditor;
            inValue.Body.sysNo = sysNo;
            inValue.Body.applier = applier;
            inValue.Body.title = title;
            inValue.Body.subTitle = subTitle;
            inValue.Body.fromTime = fromTime;
            inValue.Body.toTime = toTime;
            inValue.Body.auditResult = auditResult;
            inValue.Body.finalResult = finalResult;
            inValue.Body.billTypes = billTypes;
            inValue.Body.maxReturnCount = maxReturnCount;
            EmpInfo.FlowSvr.GetAuditListResponse retVal = ((EmpInfo.FlowSvr.FlowSvrSoap)(this)).GetAuditList(inValue);
            return retVal.Body.GetAuditListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.FlowSvr.GetMyApplyCountResponse EmpInfo.FlowSvr.FlowSvrSoap.GetMyApplyCount(EmpInfo.FlowSvr.GetMyApplyCountRequest request) {
            return base.Channel.GetMyApplyCount(request);
        }
        
        public int GetMyApplyCount(string applier, EmpInfo.FlowSvr.ArrayOfString billType) {
            EmpInfo.FlowSvr.GetMyApplyCountRequest inValue = new EmpInfo.FlowSvr.GetMyApplyCountRequest();
            inValue.Body = new EmpInfo.FlowSvr.GetMyApplyCountRequestBody();
            inValue.Body.applier = applier;
            inValue.Body.billType = billType;
            EmpInfo.FlowSvr.GetMyApplyCountResponse retVal = ((EmpInfo.FlowSvr.FlowSvrSoap)(this)).GetMyApplyCount(inValue);
            return retVal.Body.GetMyApplyCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.FlowSvr.GetMyDealingApplyCountResponse EmpInfo.FlowSvr.FlowSvrSoap.GetMyDealingApplyCount(EmpInfo.FlowSvr.GetMyDealingApplyCountRequest request) {
            return base.Channel.GetMyDealingApplyCount(request);
        }
        
        public int GetMyDealingApplyCount(string auditor, EmpInfo.FlowSvr.ArrayOfString billType) {
            EmpInfo.FlowSvr.GetMyDealingApplyCountRequest inValue = new EmpInfo.FlowSvr.GetMyDealingApplyCountRequest();
            inValue.Body = new EmpInfo.FlowSvr.GetMyDealingApplyCountRequestBody();
            inValue.Body.auditor = auditor;
            inValue.Body.billType = billType;
            EmpInfo.FlowSvr.GetMyDealingApplyCountResponse retVal = ((EmpInfo.FlowSvr.FlowSvrSoap)(this)).GetMyDealingApplyCount(inValue);
            return retVal.Body.GetMyDealingApplyCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.FlowSvr.GetCurrentStepResponse EmpInfo.FlowSvr.FlowSvrSoap.GetCurrentStep(EmpInfo.FlowSvr.GetCurrentStepRequest request) {
            return base.Channel.GetCurrentStep(request);
        }
        
        public EmpInfo.FlowSvr.CurrentAuditModel GetCurrentStep(string sysNo) {
            EmpInfo.FlowSvr.GetCurrentStepRequest inValue = new EmpInfo.FlowSvr.GetCurrentStepRequest();
            inValue.Body = new EmpInfo.FlowSvr.GetCurrentStepRequestBody();
            inValue.Body.sysNo = sysNo;
            EmpInfo.FlowSvr.GetCurrentStepResponse retVal = ((EmpInfo.FlowSvr.FlowSvrSoap)(this)).GetCurrentStep(inValue);
            return retVal.Body.GetCurrentStepResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.FlowSvr.AbortFlowResponse EmpInfo.FlowSvr.FlowSvrSoap.AbortFlow(EmpInfo.FlowSvr.AbortFlowRequest request) {
            return base.Channel.AbortFlow(request);
        }
        
        public EmpInfo.FlowSvr.FlowResultModel AbortFlow(string userNumber, string sysNo) {
            EmpInfo.FlowSvr.AbortFlowRequest inValue = new EmpInfo.FlowSvr.AbortFlowRequest();
            inValue.Body = new EmpInfo.FlowSvr.AbortFlowRequestBody();
            inValue.Body.userNumber = userNumber;
            inValue.Body.sysNo = sysNo;
            EmpInfo.FlowSvr.AbortFlowResponse retVal = ((EmpInfo.FlowSvr.FlowSvrSoap)(this)).AbortFlow(inValue);
            return retVal.Body.AbortFlowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.FlowSvr.TestStarFlowResponse EmpInfo.FlowSvr.FlowSvrSoap.TestStarFlow(EmpInfo.FlowSvr.TestStarFlowRequest request) {
            return base.Channel.TestStarFlow(request);
        }
        
        public EmpInfo.FlowSvr.FlowResultModel TestStarFlow() {
            EmpInfo.FlowSvr.TestStarFlowRequest inValue = new EmpInfo.FlowSvr.TestStarFlowRequest();
            inValue.Body = new EmpInfo.FlowSvr.TestStarFlowRequestBody();
            EmpInfo.FlowSvr.TestStarFlowResponse retVal = ((EmpInfo.FlowSvr.FlowSvrSoap)(this)).TestStarFlow(inValue);
            return retVal.Body.TestStarFlowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.FlowSvr.TestAuditResponse EmpInfo.FlowSvr.FlowSvrSoap.TestAudit(EmpInfo.FlowSvr.TestAuditRequest request) {
            return base.Channel.TestAudit(request);
        }
        
        public EmpInfo.FlowSvr.FlowResultModel TestAudit() {
            EmpInfo.FlowSvr.TestAuditRequest inValue = new EmpInfo.FlowSvr.TestAuditRequest();
            inValue.Body = new EmpInfo.FlowSvr.TestAuditRequestBody();
            EmpInfo.FlowSvr.TestAuditResponse retVal = ((EmpInfo.FlowSvr.FlowSvrSoap)(this)).TestAudit(inValue);
            return retVal.Body.TestAuditResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.FlowSvr.TestFlowRecordResponse EmpInfo.FlowSvr.FlowSvrSoap.TestFlowRecord(EmpInfo.FlowSvr.TestFlowRecordRequest request) {
            return base.Channel.TestFlowRecord(request);
        }
        
        public EmpInfo.FlowSvr.FlowRecordModels[] TestFlowRecord(string sysNo) {
            EmpInfo.FlowSvr.TestFlowRecordRequest inValue = new EmpInfo.FlowSvr.TestFlowRecordRequest();
            inValue.Body = new EmpInfo.FlowSvr.TestFlowRecordRequestBody();
            inValue.Body.sysNo = sysNo;
            EmpInfo.FlowSvr.TestFlowRecordResponse retVal = ((EmpInfo.FlowSvr.FlowSvrSoap)(this)).TestFlowRecord(inValue);
            return retVal.Body.TestFlowRecordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.FlowSvr.TestFlowAuditListResponse EmpInfo.FlowSvr.FlowSvrSoap.TestFlowAuditList(EmpInfo.FlowSvr.TestFlowAuditListRequest request) {
            return base.Channel.TestFlowAuditList(request);
        }
        
        public EmpInfo.FlowSvr.FlowAuditListModel[] TestFlowAuditList(string sysNo) {
            EmpInfo.FlowSvr.TestFlowAuditListRequest inValue = new EmpInfo.FlowSvr.TestFlowAuditListRequest();
            inValue.Body = new EmpInfo.FlowSvr.TestFlowAuditListRequestBody();
            inValue.Body.sysNo = sysNo;
            EmpInfo.FlowSvr.TestFlowAuditListResponse retVal = ((EmpInfo.FlowSvr.FlowSvrSoap)(this)).TestFlowAuditList(inValue);
            return retVal.Body.TestFlowAuditListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.FlowSvr.TestMyFlowListResponse EmpInfo.FlowSvr.FlowSvrSoap.TestMyFlowList(EmpInfo.FlowSvr.TestMyFlowListRequest request) {
            return base.Channel.TestMyFlowList(request);
        }
        
        public EmpInfo.FlowSvr.FlowMyAppliesModel[] TestMyFlowList() {
            EmpInfo.FlowSvr.TestMyFlowListRequest inValue = new EmpInfo.FlowSvr.TestMyFlowListRequest();
            inValue.Body = new EmpInfo.FlowSvr.TestMyFlowListRequestBody();
            EmpInfo.FlowSvr.TestMyFlowListResponse retVal = ((EmpInfo.FlowSvr.FlowSvrSoap)(this)).TestMyFlowList(inValue);
            return retVal.Body.TestMyFlowListResult;
        }
    }
}
