//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInfo.QywxWebSrv {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TextMsg", Namespace="http://ic.truly.com.cn/")]
    [System.SerializableAttribute()]
    public partial class TextMsg : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string touserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string topartyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string totagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string agentidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EmpInfo.QywxWebSrv.TextContent textField;
        
        private System.Nullable<int> safeField;
        
        private System.Nullable<int> enable_id_transField;
        
        private System.Nullable<int> enable_duplicate_checkField;
        
        private System.Nullable<int> duplicate_check_intervalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string touser {
            get {
                return this.touserField;
            }
            set {
                if ((object.ReferenceEquals(this.touserField, value) != true)) {
                    this.touserField = value;
                    this.RaisePropertyChanged("touser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string toparty {
            get {
                return this.topartyField;
            }
            set {
                if ((object.ReferenceEquals(this.topartyField, value) != true)) {
                    this.topartyField = value;
                    this.RaisePropertyChanged("toparty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string totag {
            get {
                return this.totagField;
            }
            set {
                if ((object.ReferenceEquals(this.totagField, value) != true)) {
                    this.totagField = value;
                    this.RaisePropertyChanged("totag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string agentid {
            get {
                return this.agentidField;
            }
            set {
                if ((object.ReferenceEquals(this.agentidField, value) != true)) {
                    this.agentidField = value;
                    this.RaisePropertyChanged("agentid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public EmpInfo.QywxWebSrv.TextContent text {
            get {
                return this.textField;
            }
            set {
                if ((object.ReferenceEquals(this.textField, value) != true)) {
                    this.textField = value;
                    this.RaisePropertyChanged("text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> safe {
            get {
                return this.safeField;
            }
            set {
                if ((this.safeField.Equals(value) != true)) {
                    this.safeField = value;
                    this.RaisePropertyChanged("safe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> enable_id_trans {
            get {
                return this.enable_id_transField;
            }
            set {
                if ((this.enable_id_transField.Equals(value) != true)) {
                    this.enable_id_transField = value;
                    this.RaisePropertyChanged("enable_id_trans");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> enable_duplicate_check {
            get {
                return this.enable_duplicate_checkField;
            }
            set {
                if ((this.enable_duplicate_checkField.Equals(value) != true)) {
                    this.enable_duplicate_checkField = value;
                    this.RaisePropertyChanged("enable_duplicate_check");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<int> duplicate_check_interval {
            get {
                return this.duplicate_check_intervalField;
            }
            set {
                if ((this.duplicate_check_intervalField.Equals(value) != true)) {
                    this.duplicate_check_intervalField = value;
                    this.RaisePropertyChanged("duplicate_check_interval");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TextContent", Namespace="http://ic.truly.com.cn/")]
    [System.SerializableAttribute()]
    public partial class TextContent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                if ((object.ReferenceEquals(this.contentField, value) != true)) {
                    this.contentField = value;
                    this.RaisePropertyChanged("content");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TextCardMsg", Namespace="http://ic.truly.com.cn/")]
    [System.SerializableAttribute()]
    public partial class TextCardMsg : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string touserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string topartyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string totagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string agentidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EmpInfo.QywxWebSrv.TextCardContent textcardField;
        
        private System.Nullable<int> enable_id_transField;
        
        private System.Nullable<int> enable_duplicate_checkField;
        
        private System.Nullable<int> duplicate_check_intervalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string touser {
            get {
                return this.touserField;
            }
            set {
                if ((object.ReferenceEquals(this.touserField, value) != true)) {
                    this.touserField = value;
                    this.RaisePropertyChanged("touser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string toparty {
            get {
                return this.topartyField;
            }
            set {
                if ((object.ReferenceEquals(this.topartyField, value) != true)) {
                    this.topartyField = value;
                    this.RaisePropertyChanged("toparty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string totag {
            get {
                return this.totagField;
            }
            set {
                if ((object.ReferenceEquals(this.totagField, value) != true)) {
                    this.totagField = value;
                    this.RaisePropertyChanged("totag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string agentid {
            get {
                return this.agentidField;
            }
            set {
                if ((object.ReferenceEquals(this.agentidField, value) != true)) {
                    this.agentidField = value;
                    this.RaisePropertyChanged("agentid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public EmpInfo.QywxWebSrv.TextCardContent textcard {
            get {
                return this.textcardField;
            }
            set {
                if ((object.ReferenceEquals(this.textcardField, value) != true)) {
                    this.textcardField = value;
                    this.RaisePropertyChanged("textcard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> enable_id_trans {
            get {
                return this.enable_id_transField;
            }
            set {
                if ((this.enable_id_transField.Equals(value) != true)) {
                    this.enable_id_transField = value;
                    this.RaisePropertyChanged("enable_id_trans");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> enable_duplicate_check {
            get {
                return this.enable_duplicate_checkField;
            }
            set {
                if ((this.enable_duplicate_checkField.Equals(value) != true)) {
                    this.enable_duplicate_checkField = value;
                    this.RaisePropertyChanged("enable_duplicate_check");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> duplicate_check_interval {
            get {
                return this.duplicate_check_intervalField;
            }
            set {
                if ((this.duplicate_check_intervalField.Equals(value) != true)) {
                    this.duplicate_check_intervalField = value;
                    this.RaisePropertyChanged("duplicate_check_interval");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TextCardContent", Namespace="http://ic.truly.com.cn/")]
    [System.SerializableAttribute()]
    public partial class TextCardContent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string btntxtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                if ((object.ReferenceEquals(this.urlField, value) != true)) {
                    this.urlField = value;
                    this.RaisePropertyChanged("url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string btntxt {
            get {
                return this.btntxtField;
            }
            set {
                if ((object.ReferenceEquals(this.btntxtField, value) != true)) {
                    this.btntxtField = value;
                    this.RaisePropertyChanged("btntxt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ic.truly.com.cn/", ConfigurationName="QywxWebSrv.QywxApiSrvSoap")]
    public interface QywxApiSrvSoap {
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 secret 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/GetAccessToken", ReplyAction="*")]
        EmpInfo.QywxWebSrv.GetAccessTokenResponse GetAccessToken(EmpInfo.QywxWebSrv.GetAccessTokenRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 secret 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/GetJsApiTicket", ReplyAction="*")]
        EmpInfo.QywxWebSrv.GetJsApiTicketResponse GetJsApiTicket(EmpInfo.QywxWebSrv.GetJsApiTicketRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 secret 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/GetSignature", ReplyAction="*")]
        EmpInfo.QywxWebSrv.GetSignatureResponse GetSignature(EmpInfo.QywxWebSrv.GetSignatureRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 openId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/GetUserIdByOpenId", ReplyAction="*")]
        EmpInfo.QywxWebSrv.GetUserIdByOpenIdResponse GetUserIdByOpenId(EmpInfo.QywxWebSrv.GetUserIdByOpenIdRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 userId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/GetOpenIdByUserId", ReplyAction="*")]
        EmpInfo.QywxWebSrv.GetOpenIdByUserIdResponse GetOpenIdByUserId(EmpInfo.QywxWebSrv.GetOpenIdByUserIdRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 redirectUrl 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/GetOAthLink", ReplyAction="*")]
        EmpInfo.QywxWebSrv.GetOAthLinkResponse GetOAthLink(EmpInfo.QywxWebSrv.GetOAthLinkRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 agentId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/GetWebLink", ReplyAction="*")]
        EmpInfo.QywxWebSrv.GetWebLinkResponse GetWebLink(EmpInfo.QywxWebSrv.GetWebLinkRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 secret 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/GetUserIdFromCode", ReplyAction="*")]
        EmpInfo.QywxWebSrv.GetUserIdFromCodeResponse GetUserIdFromCode(EmpInfo.QywxWebSrv.GetUserIdFromCodeRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/GetVarifyMsg", ReplyAction="*")]
        EmpInfo.QywxWebSrv.GetVarifyMsgResponse GetVarifyMsg(EmpInfo.QywxWebSrv.GetVarifyMsgRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/GetDecryptMsg", ReplyAction="*")]
        EmpInfo.QywxWebSrv.GetDecryptMsgResponse GetDecryptMsg(EmpInfo.QywxWebSrv.GetDecryptMsgRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/GetEncryptMsg", ReplyAction="*")]
        EmpInfo.QywxWebSrv.GetEncryptMsgResponse GetEncryptMsg(EmpInfo.QywxWebSrv.GetEncryptMsgRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 secret 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/PushTextMsg", ReplyAction="*")]
        EmpInfo.QywxWebSrv.PushTextMsgResponse PushTextMsg(EmpInfo.QywxWebSrv.PushTextMsgRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 secret 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/PushTextCardMsg", ReplyAction="*")]
        EmpInfo.QywxWebSrv.PushTextCardMsgResponse PushTextCardMsg(EmpInfo.QywxWebSrv.PushTextCardMsgRequest request);
        
        // CODEGEN: 命名空间 http://ic.truly.com.cn/ 的元素名称 content 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ic.truly.com.cn/TestPush", ReplyAction="*")]
        EmpInfo.QywxWebSrv.TestPushResponse TestPush(EmpInfo.QywxWebSrv.TestPushRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccessTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccessToken", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.GetAccessTokenRequestBody Body;
        
        public GetAccessTokenRequest() {
        }
        
        public GetAccessTokenRequest(EmpInfo.QywxWebSrv.GetAccessTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetAccessTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string secret;
        
        public GetAccessTokenRequestBody() {
        }
        
        public GetAccessTokenRequestBody(string secret) {
            this.secret = secret;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccessTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccessTokenResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.GetAccessTokenResponseBody Body;
        
        public GetAccessTokenResponse() {
        }
        
        public GetAccessTokenResponse(EmpInfo.QywxWebSrv.GetAccessTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetAccessTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAccessTokenResult;
        
        public GetAccessTokenResponseBody() {
        }
        
        public GetAccessTokenResponseBody(string GetAccessTokenResult) {
            this.GetAccessTokenResult = GetAccessTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetJsApiTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetJsApiTicket", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.GetJsApiTicketRequestBody Body;
        
        public GetJsApiTicketRequest() {
        }
        
        public GetJsApiTicketRequest(EmpInfo.QywxWebSrv.GetJsApiTicketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetJsApiTicketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string secret;
        
        public GetJsApiTicketRequestBody() {
        }
        
        public GetJsApiTicketRequestBody(string secret) {
            this.secret = secret;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetJsApiTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetJsApiTicketResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.GetJsApiTicketResponseBody Body;
        
        public GetJsApiTicketResponse() {
        }
        
        public GetJsApiTicketResponse(EmpInfo.QywxWebSrv.GetJsApiTicketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetJsApiTicketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetJsApiTicketResult;
        
        public GetJsApiTicketResponseBody() {
        }
        
        public GetJsApiTicketResponseBody(string GetJsApiTicketResult) {
            this.GetJsApiTicketResult = GetJsApiTicketResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSignatureRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSignature", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.GetSignatureRequestBody Body;
        
        public GetSignatureRequest() {
        }
        
        public GetSignatureRequest(EmpInfo.QywxWebSrv.GetSignatureRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetSignatureRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string secret;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string noncestr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string timestamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string url;
        
        public GetSignatureRequestBody() {
        }
        
        public GetSignatureRequestBody(string secret, string noncestr, string timestamp, string url) {
            this.secret = secret;
            this.noncestr = noncestr;
            this.timestamp = timestamp;
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSignatureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSignatureResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.GetSignatureResponseBody Body;
        
        public GetSignatureResponse() {
        }
        
        public GetSignatureResponse(EmpInfo.QywxWebSrv.GetSignatureResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetSignatureResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSignatureResult;
        
        public GetSignatureResponseBody() {
        }
        
        public GetSignatureResponseBody(string GetSignatureResult) {
            this.GetSignatureResult = GetSignatureResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserIdByOpenIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserIdByOpenId", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.GetUserIdByOpenIdRequestBody Body;
        
        public GetUserIdByOpenIdRequest() {
        }
        
        public GetUserIdByOpenIdRequest(EmpInfo.QywxWebSrv.GetUserIdByOpenIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetUserIdByOpenIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string openId;
        
        public GetUserIdByOpenIdRequestBody() {
        }
        
        public GetUserIdByOpenIdRequestBody(string openId) {
            this.openId = openId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserIdByOpenIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserIdByOpenIdResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.GetUserIdByOpenIdResponseBody Body;
        
        public GetUserIdByOpenIdResponse() {
        }
        
        public GetUserIdByOpenIdResponse(EmpInfo.QywxWebSrv.GetUserIdByOpenIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetUserIdByOpenIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserIdByOpenIdResult;
        
        public GetUserIdByOpenIdResponseBody() {
        }
        
        public GetUserIdByOpenIdResponseBody(string GetUserIdByOpenIdResult) {
            this.GetUserIdByOpenIdResult = GetUserIdByOpenIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOpenIdByUserIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOpenIdByUserId", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.GetOpenIdByUserIdRequestBody Body;
        
        public GetOpenIdByUserIdRequest() {
        }
        
        public GetOpenIdByUserIdRequest(EmpInfo.QywxWebSrv.GetOpenIdByUserIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetOpenIdByUserIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        public GetOpenIdByUserIdRequestBody() {
        }
        
        public GetOpenIdByUserIdRequestBody(string userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOpenIdByUserIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOpenIdByUserIdResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.GetOpenIdByUserIdResponseBody Body;
        
        public GetOpenIdByUserIdResponse() {
        }
        
        public GetOpenIdByUserIdResponse(EmpInfo.QywxWebSrv.GetOpenIdByUserIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetOpenIdByUserIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetOpenIdByUserIdResult;
        
        public GetOpenIdByUserIdResponseBody() {
        }
        
        public GetOpenIdByUserIdResponseBody(string GetOpenIdByUserIdResult) {
            this.GetOpenIdByUserIdResult = GetOpenIdByUserIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOAthLinkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOAthLink", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.GetOAthLinkRequestBody Body;
        
        public GetOAthLinkRequest() {
        }
        
        public GetOAthLinkRequest(EmpInfo.QywxWebSrv.GetOAthLinkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetOAthLinkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string redirectUrl;
        
        public GetOAthLinkRequestBody() {
        }
        
        public GetOAthLinkRequestBody(string redirectUrl) {
            this.redirectUrl = redirectUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOAthLinkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOAthLinkResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.GetOAthLinkResponseBody Body;
        
        public GetOAthLinkResponse() {
        }
        
        public GetOAthLinkResponse(EmpInfo.QywxWebSrv.GetOAthLinkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetOAthLinkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetOAthLinkResult;
        
        public GetOAthLinkResponseBody() {
        }
        
        public GetOAthLinkResponseBody(string GetOAthLinkResult) {
            this.GetOAthLinkResult = GetOAthLinkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWebLinkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWebLink", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.GetWebLinkRequestBody Body;
        
        public GetWebLinkRequest() {
        }
        
        public GetWebLinkRequest(EmpInfo.QywxWebSrv.GetWebLinkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetWebLinkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string agentId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string redirectUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string state;
        
        public GetWebLinkRequestBody() {
        }
        
        public GetWebLinkRequestBody(string agentId, string redirectUrl, string state) {
            this.agentId = agentId;
            this.redirectUrl = redirectUrl;
            this.state = state;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWebLinkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWebLinkResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.GetWebLinkResponseBody Body;
        
        public GetWebLinkResponse() {
        }
        
        public GetWebLinkResponse(EmpInfo.QywxWebSrv.GetWebLinkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetWebLinkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetWebLinkResult;
        
        public GetWebLinkResponseBody() {
        }
        
        public GetWebLinkResponseBody(string GetWebLinkResult) {
            this.GetWebLinkResult = GetWebLinkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserIdFromCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserIdFromCode", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.GetUserIdFromCodeRequestBody Body;
        
        public GetUserIdFromCodeRequest() {
        }
        
        public GetUserIdFromCodeRequest(EmpInfo.QywxWebSrv.GetUserIdFromCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetUserIdFromCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string secret;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string code;
        
        public GetUserIdFromCodeRequestBody() {
        }
        
        public GetUserIdFromCodeRequestBody(string secret, string code) {
            this.secret = secret;
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserIdFromCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserIdFromCodeResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.GetUserIdFromCodeResponseBody Body;
        
        public GetUserIdFromCodeResponse() {
        }
        
        public GetUserIdFromCodeResponse(EmpInfo.QywxWebSrv.GetUserIdFromCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetUserIdFromCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserIdFromCodeResult;
        
        public GetUserIdFromCodeResponseBody() {
        }
        
        public GetUserIdFromCodeResponseBody(string GetUserIdFromCodeResult) {
            this.GetUserIdFromCodeResult = GetUserIdFromCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVarifyMsgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVarifyMsg", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.GetVarifyMsgRequestBody Body;
        
        public GetVarifyMsgRequest() {
        }
        
        public GetVarifyMsgRequest(EmpInfo.QywxWebSrv.GetVarifyMsgRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetVarifyMsgRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string encodingAESKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string msg_signature;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string timestamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string nonce;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string echostr;
        
        public GetVarifyMsgRequestBody() {
        }
        
        public GetVarifyMsgRequestBody(string token, string encodingAESKey, string msg_signature, string timestamp, string nonce, string echostr) {
            this.token = token;
            this.encodingAESKey = encodingAESKey;
            this.msg_signature = msg_signature;
            this.timestamp = timestamp;
            this.nonce = nonce;
            this.echostr = echostr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVarifyMsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVarifyMsgResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.GetVarifyMsgResponseBody Body;
        
        public GetVarifyMsgResponse() {
        }
        
        public GetVarifyMsgResponse(EmpInfo.QywxWebSrv.GetVarifyMsgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetVarifyMsgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetVarifyMsgResult;
        
        public GetVarifyMsgResponseBody() {
        }
        
        public GetVarifyMsgResponseBody(string GetVarifyMsgResult) {
            this.GetVarifyMsgResult = GetVarifyMsgResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDecryptMsgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDecryptMsg", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.GetDecryptMsgRequestBody Body;
        
        public GetDecryptMsgRequest() {
        }
        
        public GetDecryptMsgRequest(EmpInfo.QywxWebSrv.GetDecryptMsgRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetDecryptMsgRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string encodingAESKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string msg_signature;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string timestamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string nonce;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string post_data;
        
        public GetDecryptMsgRequestBody() {
        }
        
        public GetDecryptMsgRequestBody(string token, string encodingAESKey, string msg_signature, string timestamp, string nonce, string post_data) {
            this.token = token;
            this.encodingAESKey = encodingAESKey;
            this.msg_signature = msg_signature;
            this.timestamp = timestamp;
            this.nonce = nonce;
            this.post_data = post_data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDecryptMsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDecryptMsgResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.GetDecryptMsgResponseBody Body;
        
        public GetDecryptMsgResponse() {
        }
        
        public GetDecryptMsgResponse(EmpInfo.QywxWebSrv.GetDecryptMsgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetDecryptMsgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDecryptMsgResult;
        
        public GetDecryptMsgResponseBody() {
        }
        
        public GetDecryptMsgResponseBody(string GetDecryptMsgResult) {
            this.GetDecryptMsgResult = GetDecryptMsgResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEncryptMsgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEncryptMsg", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.GetEncryptMsgRequestBody Body;
        
        public GetEncryptMsgRequest() {
        }
        
        public GetEncryptMsgRequest(EmpInfo.QywxWebSrv.GetEncryptMsgRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetEncryptMsgRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string encodingAESKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string timestamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nonce;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string replyData;
        
        public GetEncryptMsgRequestBody() {
        }
        
        public GetEncryptMsgRequestBody(string token, string encodingAESKey, string timestamp, string nonce, string replyData) {
            this.token = token;
            this.encodingAESKey = encodingAESKey;
            this.timestamp = timestamp;
            this.nonce = nonce;
            this.replyData = replyData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEncryptMsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEncryptMsgResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.GetEncryptMsgResponseBody Body;
        
        public GetEncryptMsgResponse() {
        }
        
        public GetEncryptMsgResponse(EmpInfo.QywxWebSrv.GetEncryptMsgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class GetEncryptMsgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetEncryptMsgResult;
        
        public GetEncryptMsgResponseBody() {
        }
        
        public GetEncryptMsgResponseBody(string GetEncryptMsgResult) {
            this.GetEncryptMsgResult = GetEncryptMsgResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PushTextMsgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PushTextMsg", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.PushTextMsgRequestBody Body;
        
        public PushTextMsgRequest() {
        }
        
        public PushTextMsgRequest(EmpInfo.QywxWebSrv.PushTextMsgRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class PushTextMsgRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string secret;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string opUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public EmpInfo.QywxWebSrv.TextMsg textMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<System.DateTime> whenToPush;
        
        public PushTextMsgRequestBody() {
        }
        
        public PushTextMsgRequestBody(string secret, string opUserName, EmpInfo.QywxWebSrv.TextMsg textMsg, System.Nullable<System.DateTime> whenToPush) {
            this.secret = secret;
            this.opUserName = opUserName;
            this.textMsg = textMsg;
            this.whenToPush = whenToPush;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PushTextMsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PushTextMsgResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.PushTextMsgResponseBody Body;
        
        public PushTextMsgResponse() {
        }
        
        public PushTextMsgResponse(EmpInfo.QywxWebSrv.PushTextMsgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PushTextMsgResponseBody {
        
        public PushTextMsgResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PushTextCardMsgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PushTextCardMsg", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.PushTextCardMsgRequestBody Body;
        
        public PushTextCardMsgRequest() {
        }
        
        public PushTextCardMsgRequest(EmpInfo.QywxWebSrv.PushTextCardMsgRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class PushTextCardMsgRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string secret;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string opUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public EmpInfo.QywxWebSrv.TextCardMsg textCardMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<System.DateTime> whenToPush;
        
        public PushTextCardMsgRequestBody() {
        }
        
        public PushTextCardMsgRequestBody(string secret, string opUserName, EmpInfo.QywxWebSrv.TextCardMsg textCardMsg, System.Nullable<System.DateTime> whenToPush) {
            this.secret = secret;
            this.opUserName = opUserName;
            this.textCardMsg = textCardMsg;
            this.whenToPush = whenToPush;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PushTextCardMsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PushTextCardMsgResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.PushTextCardMsgResponseBody Body;
        
        public PushTextCardMsgResponse() {
        }
        
        public PushTextCardMsgResponse(EmpInfo.QywxWebSrv.PushTextCardMsgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PushTextCardMsgResponseBody {
        
        public PushTextCardMsgResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestPushRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestPush", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.TestPushRequestBody Body;
        
        public TestPushRequest() {
        }
        
        public TestPushRequest(EmpInfo.QywxWebSrv.TestPushRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ic.truly.com.cn/")]
    public partial class TestPushRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string content;
        
        public TestPushRequestBody() {
        }
        
        public TestPushRequestBody(string content) {
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestPushResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestPushResponse", Namespace="http://ic.truly.com.cn/", Order=0)]
        public EmpInfo.QywxWebSrv.TestPushResponseBody Body;
        
        public TestPushResponse() {
        }
        
        public TestPushResponse(EmpInfo.QywxWebSrv.TestPushResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestPushResponseBody {
        
        public TestPushResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QywxApiSrvSoapChannel : EmpInfo.QywxWebSrv.QywxApiSrvSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QywxApiSrvSoapClient : System.ServiceModel.ClientBase<EmpInfo.QywxWebSrv.QywxApiSrvSoap>, EmpInfo.QywxWebSrv.QywxApiSrvSoap {
        
        public QywxApiSrvSoapClient() {
        }
        
        public QywxApiSrvSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QywxApiSrvSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QywxApiSrvSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QywxApiSrvSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.QywxWebSrv.GetAccessTokenResponse EmpInfo.QywxWebSrv.QywxApiSrvSoap.GetAccessToken(EmpInfo.QywxWebSrv.GetAccessTokenRequest request) {
            return base.Channel.GetAccessToken(request);
        }
        
        public string GetAccessToken(string secret) {
            EmpInfo.QywxWebSrv.GetAccessTokenRequest inValue = new EmpInfo.QywxWebSrv.GetAccessTokenRequest();
            inValue.Body = new EmpInfo.QywxWebSrv.GetAccessTokenRequestBody();
            inValue.Body.secret = secret;
            EmpInfo.QywxWebSrv.GetAccessTokenResponse retVal = ((EmpInfo.QywxWebSrv.QywxApiSrvSoap)(this)).GetAccessToken(inValue);
            return retVal.Body.GetAccessTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.QywxWebSrv.GetJsApiTicketResponse EmpInfo.QywxWebSrv.QywxApiSrvSoap.GetJsApiTicket(EmpInfo.QywxWebSrv.GetJsApiTicketRequest request) {
            return base.Channel.GetJsApiTicket(request);
        }
        
        public string GetJsApiTicket(string secret) {
            EmpInfo.QywxWebSrv.GetJsApiTicketRequest inValue = new EmpInfo.QywxWebSrv.GetJsApiTicketRequest();
            inValue.Body = new EmpInfo.QywxWebSrv.GetJsApiTicketRequestBody();
            inValue.Body.secret = secret;
            EmpInfo.QywxWebSrv.GetJsApiTicketResponse retVal = ((EmpInfo.QywxWebSrv.QywxApiSrvSoap)(this)).GetJsApiTicket(inValue);
            return retVal.Body.GetJsApiTicketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.QywxWebSrv.GetSignatureResponse EmpInfo.QywxWebSrv.QywxApiSrvSoap.GetSignature(EmpInfo.QywxWebSrv.GetSignatureRequest request) {
            return base.Channel.GetSignature(request);
        }
        
        public string GetSignature(string secret, string noncestr, string timestamp, string url) {
            EmpInfo.QywxWebSrv.GetSignatureRequest inValue = new EmpInfo.QywxWebSrv.GetSignatureRequest();
            inValue.Body = new EmpInfo.QywxWebSrv.GetSignatureRequestBody();
            inValue.Body.secret = secret;
            inValue.Body.noncestr = noncestr;
            inValue.Body.timestamp = timestamp;
            inValue.Body.url = url;
            EmpInfo.QywxWebSrv.GetSignatureResponse retVal = ((EmpInfo.QywxWebSrv.QywxApiSrvSoap)(this)).GetSignature(inValue);
            return retVal.Body.GetSignatureResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.QywxWebSrv.GetUserIdByOpenIdResponse EmpInfo.QywxWebSrv.QywxApiSrvSoap.GetUserIdByOpenId(EmpInfo.QywxWebSrv.GetUserIdByOpenIdRequest request) {
            return base.Channel.GetUserIdByOpenId(request);
        }
        
        public string GetUserIdByOpenId(string openId) {
            EmpInfo.QywxWebSrv.GetUserIdByOpenIdRequest inValue = new EmpInfo.QywxWebSrv.GetUserIdByOpenIdRequest();
            inValue.Body = new EmpInfo.QywxWebSrv.GetUserIdByOpenIdRequestBody();
            inValue.Body.openId = openId;
            EmpInfo.QywxWebSrv.GetUserIdByOpenIdResponse retVal = ((EmpInfo.QywxWebSrv.QywxApiSrvSoap)(this)).GetUserIdByOpenId(inValue);
            return retVal.Body.GetUserIdByOpenIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.QywxWebSrv.GetOpenIdByUserIdResponse EmpInfo.QywxWebSrv.QywxApiSrvSoap.GetOpenIdByUserId(EmpInfo.QywxWebSrv.GetOpenIdByUserIdRequest request) {
            return base.Channel.GetOpenIdByUserId(request);
        }
        
        public string GetOpenIdByUserId(string userId) {
            EmpInfo.QywxWebSrv.GetOpenIdByUserIdRequest inValue = new EmpInfo.QywxWebSrv.GetOpenIdByUserIdRequest();
            inValue.Body = new EmpInfo.QywxWebSrv.GetOpenIdByUserIdRequestBody();
            inValue.Body.userId = userId;
            EmpInfo.QywxWebSrv.GetOpenIdByUserIdResponse retVal = ((EmpInfo.QywxWebSrv.QywxApiSrvSoap)(this)).GetOpenIdByUserId(inValue);
            return retVal.Body.GetOpenIdByUserIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.QywxWebSrv.GetOAthLinkResponse EmpInfo.QywxWebSrv.QywxApiSrvSoap.GetOAthLink(EmpInfo.QywxWebSrv.GetOAthLinkRequest request) {
            return base.Channel.GetOAthLink(request);
        }
        
        public string GetOAthLink(string redirectUrl) {
            EmpInfo.QywxWebSrv.GetOAthLinkRequest inValue = new EmpInfo.QywxWebSrv.GetOAthLinkRequest();
            inValue.Body = new EmpInfo.QywxWebSrv.GetOAthLinkRequestBody();
            inValue.Body.redirectUrl = redirectUrl;
            EmpInfo.QywxWebSrv.GetOAthLinkResponse retVal = ((EmpInfo.QywxWebSrv.QywxApiSrvSoap)(this)).GetOAthLink(inValue);
            return retVal.Body.GetOAthLinkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.QywxWebSrv.GetWebLinkResponse EmpInfo.QywxWebSrv.QywxApiSrvSoap.GetWebLink(EmpInfo.QywxWebSrv.GetWebLinkRequest request) {
            return base.Channel.GetWebLink(request);
        }
        
        public string GetWebLink(string agentId, string redirectUrl, string state) {
            EmpInfo.QywxWebSrv.GetWebLinkRequest inValue = new EmpInfo.QywxWebSrv.GetWebLinkRequest();
            inValue.Body = new EmpInfo.QywxWebSrv.GetWebLinkRequestBody();
            inValue.Body.agentId = agentId;
            inValue.Body.redirectUrl = redirectUrl;
            inValue.Body.state = state;
            EmpInfo.QywxWebSrv.GetWebLinkResponse retVal = ((EmpInfo.QywxWebSrv.QywxApiSrvSoap)(this)).GetWebLink(inValue);
            return retVal.Body.GetWebLinkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.QywxWebSrv.GetUserIdFromCodeResponse EmpInfo.QywxWebSrv.QywxApiSrvSoap.GetUserIdFromCode(EmpInfo.QywxWebSrv.GetUserIdFromCodeRequest request) {
            return base.Channel.GetUserIdFromCode(request);
        }
        
        public string GetUserIdFromCode(string secret, string code) {
            EmpInfo.QywxWebSrv.GetUserIdFromCodeRequest inValue = new EmpInfo.QywxWebSrv.GetUserIdFromCodeRequest();
            inValue.Body = new EmpInfo.QywxWebSrv.GetUserIdFromCodeRequestBody();
            inValue.Body.secret = secret;
            inValue.Body.code = code;
            EmpInfo.QywxWebSrv.GetUserIdFromCodeResponse retVal = ((EmpInfo.QywxWebSrv.QywxApiSrvSoap)(this)).GetUserIdFromCode(inValue);
            return retVal.Body.GetUserIdFromCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.QywxWebSrv.GetVarifyMsgResponse EmpInfo.QywxWebSrv.QywxApiSrvSoap.GetVarifyMsg(EmpInfo.QywxWebSrv.GetVarifyMsgRequest request) {
            return base.Channel.GetVarifyMsg(request);
        }
        
        public string GetVarifyMsg(string token, string encodingAESKey, string msg_signature, string timestamp, string nonce, string echostr) {
            EmpInfo.QywxWebSrv.GetVarifyMsgRequest inValue = new EmpInfo.QywxWebSrv.GetVarifyMsgRequest();
            inValue.Body = new EmpInfo.QywxWebSrv.GetVarifyMsgRequestBody();
            inValue.Body.token = token;
            inValue.Body.encodingAESKey = encodingAESKey;
            inValue.Body.msg_signature = msg_signature;
            inValue.Body.timestamp = timestamp;
            inValue.Body.nonce = nonce;
            inValue.Body.echostr = echostr;
            EmpInfo.QywxWebSrv.GetVarifyMsgResponse retVal = ((EmpInfo.QywxWebSrv.QywxApiSrvSoap)(this)).GetVarifyMsg(inValue);
            return retVal.Body.GetVarifyMsgResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.QywxWebSrv.GetDecryptMsgResponse EmpInfo.QywxWebSrv.QywxApiSrvSoap.GetDecryptMsg(EmpInfo.QywxWebSrv.GetDecryptMsgRequest request) {
            return base.Channel.GetDecryptMsg(request);
        }
        
        public string GetDecryptMsg(string token, string encodingAESKey, string msg_signature, string timestamp, string nonce, string post_data) {
            EmpInfo.QywxWebSrv.GetDecryptMsgRequest inValue = new EmpInfo.QywxWebSrv.GetDecryptMsgRequest();
            inValue.Body = new EmpInfo.QywxWebSrv.GetDecryptMsgRequestBody();
            inValue.Body.token = token;
            inValue.Body.encodingAESKey = encodingAESKey;
            inValue.Body.msg_signature = msg_signature;
            inValue.Body.timestamp = timestamp;
            inValue.Body.nonce = nonce;
            inValue.Body.post_data = post_data;
            EmpInfo.QywxWebSrv.GetDecryptMsgResponse retVal = ((EmpInfo.QywxWebSrv.QywxApiSrvSoap)(this)).GetDecryptMsg(inValue);
            return retVal.Body.GetDecryptMsgResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.QywxWebSrv.GetEncryptMsgResponse EmpInfo.QywxWebSrv.QywxApiSrvSoap.GetEncryptMsg(EmpInfo.QywxWebSrv.GetEncryptMsgRequest request) {
            return base.Channel.GetEncryptMsg(request);
        }
        
        public string GetEncryptMsg(string token, string encodingAESKey, string timestamp, string nonce, string replyData) {
            EmpInfo.QywxWebSrv.GetEncryptMsgRequest inValue = new EmpInfo.QywxWebSrv.GetEncryptMsgRequest();
            inValue.Body = new EmpInfo.QywxWebSrv.GetEncryptMsgRequestBody();
            inValue.Body.token = token;
            inValue.Body.encodingAESKey = encodingAESKey;
            inValue.Body.timestamp = timestamp;
            inValue.Body.nonce = nonce;
            inValue.Body.replyData = replyData;
            EmpInfo.QywxWebSrv.GetEncryptMsgResponse retVal = ((EmpInfo.QywxWebSrv.QywxApiSrvSoap)(this)).GetEncryptMsg(inValue);
            return retVal.Body.GetEncryptMsgResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.QywxWebSrv.PushTextMsgResponse EmpInfo.QywxWebSrv.QywxApiSrvSoap.PushTextMsg(EmpInfo.QywxWebSrv.PushTextMsgRequest request) {
            return base.Channel.PushTextMsg(request);
        }
        
        public void PushTextMsg(string secret, string opUserName, EmpInfo.QywxWebSrv.TextMsg textMsg, System.Nullable<System.DateTime> whenToPush) {
            EmpInfo.QywxWebSrv.PushTextMsgRequest inValue = new EmpInfo.QywxWebSrv.PushTextMsgRequest();
            inValue.Body = new EmpInfo.QywxWebSrv.PushTextMsgRequestBody();
            inValue.Body.secret = secret;
            inValue.Body.opUserName = opUserName;
            inValue.Body.textMsg = textMsg;
            inValue.Body.whenToPush = whenToPush;
            EmpInfo.QywxWebSrv.PushTextMsgResponse retVal = ((EmpInfo.QywxWebSrv.QywxApiSrvSoap)(this)).PushTextMsg(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.QywxWebSrv.PushTextCardMsgResponse EmpInfo.QywxWebSrv.QywxApiSrvSoap.PushTextCardMsg(EmpInfo.QywxWebSrv.PushTextCardMsgRequest request) {
            return base.Channel.PushTextCardMsg(request);
        }
        
        public void PushTextCardMsg(string secret, string opUserName, EmpInfo.QywxWebSrv.TextCardMsg textCardMsg, System.Nullable<System.DateTime> whenToPush) {
            EmpInfo.QywxWebSrv.PushTextCardMsgRequest inValue = new EmpInfo.QywxWebSrv.PushTextCardMsgRequest();
            inValue.Body = new EmpInfo.QywxWebSrv.PushTextCardMsgRequestBody();
            inValue.Body.secret = secret;
            inValue.Body.opUserName = opUserName;
            inValue.Body.textCardMsg = textCardMsg;
            inValue.Body.whenToPush = whenToPush;
            EmpInfo.QywxWebSrv.PushTextCardMsgResponse retVal = ((EmpInfo.QywxWebSrv.QywxApiSrvSoap)(this)).PushTextCardMsg(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpInfo.QywxWebSrv.TestPushResponse EmpInfo.QywxWebSrv.QywxApiSrvSoap.TestPush(EmpInfo.QywxWebSrv.TestPushRequest request) {
            return base.Channel.TestPush(request);
        }
        
        public void TestPush(string content) {
            EmpInfo.QywxWebSrv.TestPushRequest inValue = new EmpInfo.QywxWebSrv.TestPushRequest();
            inValue.Body = new EmpInfo.QywxWebSrv.TestPushRequestBody();
            inValue.Body.content = content;
            EmpInfo.QywxWebSrv.TestPushResponse retVal = ((EmpInfo.QywxWebSrv.QywxApiSrvSoap)(this)).TestPush(inValue);
        }
    }
}
